Quarantined changes
reblaze/ui pull request #104
Opened 2022-10-26 08:17 UTC by ux-AylonS

New checkbox in rbzTABLE FOR Quarantined page

2022-10-26 14:59 UTC, ux-AylonS commented on src/components/QuarantinedList.vue
> +                  'options': {'filter': {'config': 'prod'}},
need to bring selectedBranch

2022-10-27 07:59 UTC, Aviv-Galmidi requested changes

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> +      selectBox: true,
Not being used anywhere

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +    showCheckbox: Boolean,
```suggestion
    showCheckboxColumn: Boolean,
```

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +                      @change="() => rowSelected(row.id)" />
```suggestion
                      @change="rowSelected(row.id)" />
```

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +              <div class="dropdown-content width-140px py-0">
Don't change this for every table, rather make it into a customizable width for when we need it to be wider

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +    allCheckboxes() {
This can be a const inside `selectAll` function as it's not being used anywhere else

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +      return this.data.map((item) => item.id)
We only need to select the currently filtered data, so we should run on `this.dataArrayDisplay`

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +      this.$emit('select-array', JSON.parse(JSON.stringify(this.selectedArray)))
```suggestion
      this.$emit('select-array', _.cloneDeep(this.selectedArray))
```

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +      this.$emit('select-array', JSON.parse(JSON.stringify(this.selectedArray)))
```suggestion
      this.$emit('select-array', _.cloneDeep(this.selectedArray))
```

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +          this.selectedArray = [...this.allCheckboxes]
This can be taken out of the for, we're setting `this.selectedArray` to equal the same array over and over again

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +      this.isSelected= !this.isSelected
consider the following scenario
1. Open new Quarantined page
2. Click title checkbox to select all
3. Click row checkbox to deslect a single row
The title checkbox is still marked even though we no longer have all selected

`isSelected` should probably be a computed value - on get check if all checkbox are marked, on set - if all checkboxes are marked demark them, if not then mark them all

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +  emits: ['new-button-clicked', 'row-button-clicked', 'show-checkbox', 'row-clicked', 'select-array'],
You don't emit `show-checkbox`

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/types/index.d.ts
> +    checkbox?: boolean
Leftover from the first solution attempt?

2022-10-27 07:59 UTC, Aviv-Galmidi commented on src/types/index.d.ts
> +  type SelectedRow = {id: string, selected: boolean}
Leftover code no longer in use?

2022-10-27 08:40 UTC, ux-AylonS commented on .gitignore
> +src/components/db.txt
text for insert data into the quarantined db
can be removed from the repo

2022-10-27 09:20 UTC, ux-AylonS commented on src/components/QuarantinedList.vue
> -        {
we did not had it before, but I am adding ID.

2022-10-27 10:13 UTC, ux-AylonS commented on src/components/RbzTable.vue
> +      this.isSelected= !this.isSelected
fixed

2022-10-27 10:15 UTC, ux-AylonS commented on src/types/index.d.ts
> +    checkbox?: boolean
great catch.

2022-10-30 16:36 UTC, Aviv-Galmidi requested changes
Please also remove the file `src/components/test.html`

2022-10-30 16:36 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> +    await this.loadQuarantinedData()
This needs to move to a watch on selectedBranch similar to all the other pages, otherwise if you're in this page and change a branch the data won't be relaoded

2022-10-30 19:26 UTC, Aviv-Galmidi submitted a review, later dismissed

2022-10-30 20:04 UTC, Aviv-Galmidi commented
The red color for the trash icon was added to all RbzTable buttons - fixed. Now it's inside a prop we can pass `row-button-class` which includes all classes we'll ever need to add to this button

The Quarantine table doens't look good right now. Added a picture
* ID column is way too small
* "No data found" message doesn't expand to the entire row
* No fixed widths in clumns. From the task "Add fixed width to all columns (Up to one column can have no width if needed)" * We cannot have so many columns with no widths, that screws up the page flow with long data and makes the columns jump around depending on the data inserted
<img width="1434" alt="Screen Shot 2022-10-30 at 21 43 11" src="https://user-images.githubusercontent.com/10487148/198899107-f9cb68a1-836c-4a4b-bc96-86d204ec3ecc.png">

2022-10-31 09:02 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> -                 row-button-icon="fa-trash"
There's no need to send these props with dynamic data
`row-button-icon="fa-trash"` is the same as `:row-button-icon="'fa-trash'"`

2022-10-31 10:29 UTC, Aviv-Galmidi commented
Still missing some widths

No data:
<img width="1440" alt="Screen Shot 2022-10-31 at 12 16 51" src="https://user-images.githubusercontent.com/10487148/198987044-38077ff2-eb5b-4896-9fbc-8617ddd7202a.png">

Width data:
<img width="1440" alt="Screen Shot 2022-10-31 at 12 25 19" src="https://user-images.githubusercontent.com/10487148/198987075-0de0a627-34a4-48aa-bb20-bd3321393438.png">

The column widths shouldn't change whether there is data or not
`Key Parameter` shouldn't have a line-break in the column header
If `Count` and `Rules` columns are numbers then they're missing the `isNumber: true` prop

2022-10-31 10:41 UTC, Aviv-Galmidi commented
More notes:

Checkbox column is missing the filter cell which pushes all other filters by one
<img width="1440" alt="Screen Shot 2022-10-31 at 12 32 36" src="https://user-images.githubusercontent.com/10487148/198988269-2d4cf09a-6daf-4fc6-80d4-92b4448d2890.png">

Design for the `Delete Selected` button should match the other menu buttons (It has border and hover background color, not sure what else is different)
<img width="190" alt="Screen Shot 2022-10-31 at 12 33 19" src="https://user-images.githubusercontent.com/10487148/198988386-5c81fa1d-3cc6-4d5b-baf0-563254ed93d2.png">

When filtering, we should unselect elements not displayed anymore to avoid the following scenario
1. Select first element
2. Filter out first element
3. Select second element
4. Delete all selected
5. Remove filter
Expected: Just the currently filtered and selected value should be removed
Actual: Both items are removed

Clicking `Select All` in the title when there are multiple pages throws an error

2022-11-03 07:18 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> +<style scoped
Fix indents, class declerations should be aligned to the left

2022-11-03 07:20 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +        <div class="field is-grouped is-grouped-centered">
We can probably remove this div

2022-11-03 07:20 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +      // slicedDataArrayDisplay: [] as GenericObject[],
?

2022-11-03 07:56 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +        }
```suggestion
        if (val?.length > 0 && this.selectedArray?.length > 0) {
          const valIdArray = val.map((row: any) => row.id)
          this.selectedArray = _.filter(this.selectedArray, (selectedArrayItem) => {
            return _.some(val, (dataArrayItem) => {
              return dataArrayItem.id === selectedArrayItem.id
            })
          })
        } else {
          this.selectedArray = []
        }
```

2022-11-03 07:57 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +      const currentCheckboxes = this.dataArrayDisplay.map((item) => item.id)
```suggestion
      const currentCheckboxes = _.map(this.dataArrayDisplay, 'id')
```

2022-11-03 08:29 UTC, ux-AylonS commented on src/components/RbzTable.vue
> +      // slicedDataArrayDisplay: [] as GenericObject[],
sorry, leftover from my other solution.

2022-11-03 09:29 UTC, Aviv-Galmidi commented
`Select All` checkbox doesn’t light up when you manually select all

https://user-images.githubusercontent.com/10487148/199686485-513fea57-534a-42a7-87cd-7620799b56ca.mov



Filter does not remove items from the selected array

https://user-images.githubusercontent.com/10487148/199686557-66efcbd4-871e-4cef-be31-d497267f9dc7.mov



`Select All` checkbox does not reset when filtering data

https://user-images.githubusercontent.com/10487148/199686872-48c5b926-410d-4abd-8b1d-de3f44e4c443.mov

2022-11-06 07:17 UTC, Aviv-Galmidi commented
`Select All` randomly lights up

https://user-images.githubusercontent.com/10487148/200158886-af96cab5-f9e6-4490-900e-4374c089ff4c.mov

Filter does not remove items from the selected array

https://user-images.githubusercontent.com/10487148/200158888-18f7d6bf-0cfb-499a-8385-53cd5b4eb981.mov

Still not working as expected, please make sure the feature works properly for all cases

2022-11-06 13:34 UTC, Aviv-Galmidi requested changes

2022-11-06 13:34 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +        let selectedArrayTemp = []
Can we get rid of the temp variables here?
Assign the filtered array directly to `this.selectedArray` and return `_.includes...` instead of setting it to a temp variable called `temp`

2022-11-06 13:41 UTC, Aviv-Galmidi approved these changes
If all the checks pass below, we can merge this

2022-11-06 14:06 UTC, merged