Tags validation
reblaze/ui pull request #111
Opened 2022-10-27 17:29 UTC by ux-AylonS

2022-10-30 08:17 UTC, Aviv-Galmidi requested changes

2022-10-30 08:17 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +    isValidDocWithTags(): boolean {
This is not the right approach, a document might not have the `tags` field at all but still require it (If it was created through the API for instance), each document should manage its own tag validation

> In pages that are using DocumentEditor we can achieve that by emitting `form-invalid` from inside the editor component

Missing the initial tag in datasetsUtils

> In addition, all of these entities should have a default tag added to them on creation (in datasetsUtils)

2022-10-30 08:17 UTC, Aviv-Galmidi commented on src/views/DocumentList.vue
> -import {COLUMN_OPTIONS_MAP} from './documentListConst'
This is being used in line 215
https://github.com/reblaze/ui/blob/main/src/views/DocumentList.vue#L215

2022-10-30 12:43 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +    isValidDocWithTags(): boolean {
what is the default values for tags for each document tag?
is there a default action? what is it?
or where I can find it?

2022-11-06 04:47 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +    isValidDocWithTags(): boolean {
deleted

2022-11-06 13:39 UTC, Aviv-Galmidi requested changes

2022-11-06 13:39 UTC, Aviv-Galmidi commented on src/components/AutocompleteInput.vue
> +    isValid(): boolean {
We do not need to apply this validation on ALL autocomplete inputs, but specifically on `tags` inputs. Note that it does not mean we should apply this on `TagAutoComplete` either as it is being used in other inputs field which need tags and are not labelled as `tags` inputs, such as `include` or `exclude`

2022-11-06 13:39 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +    getIsDocumentInvalid(isDocumentInvalid: boolean) {
Did you mean `set`? This function doesn't do `get` at the moment

2022-11-06 13:39 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +                        :title="tagsInvalid ? 'Missing a tag' : 'Save changes'"
Let's move this to a computed value

2022-11-06 16:14 UTC, ux-AylonS commented on src/components/AutocompleteInput.vue
> +    isValid(): boolean {
moved all the logic to the Editor

2022-11-08 07:35 UTC, Aviv-Galmidi requested changes

2022-11-08 07:35 UTC, Aviv-Galmidi commented on src/components/AutocompleteInput.vue
> +  emits: ['invalid', 'value-changed', 'value-submitted', 'keyup', 'keydown', 'keypress', 'focus', 'blur'],
the component doesn't emit `invalid` (It didn't emit `tag-changed` either, that was a mistake)

2022-11-08 07:35 UTC, Aviv-Galmidi commented on src/components/TagAutocompleteInput.vue
>        :minimum-value-length="minimumTagLength"
Why did you change `tagChanged` and `tagSubmitted` names and emits?

In `TagAutocompleteInput` they value is always tag, so the previous name is more accurate

2022-11-08 07:35 UTC, Aviv-Galmidi commented on src/doc-editors/ACLEditor.vue
> +                                              v-model="selectedDocTags"
What is the `v-model` supposed to do? We don't use `modelValue` in `TagAutocompleteInput` so I think that might be redundant

2022-11-08 07:35 UTC, Aviv-Galmidi commented on src/doc-editors/ACLEditor.vue
> +        this.$emit('tags-invalid', true)
Why do you emit tags are invalid on get, doesn't that cause the save button to be disabled on initial load until the user edits the existing tags?

2022-11-08 07:35 UTC, Aviv-Galmidi commented on src/doc-editors/ACLEditor.vue
> +        if (tags.trim() == '' || tags.length < 3) {
Instead of this check, you can run the check directly on `this.localDoc.tags` which is an array of tags, we know the length must be at least 1

2022-11-08 07:35 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +          @form-invalid="setIsDocumentInvalid"
If we created `setIsDocumentInvalid` function, let's do the same to the `tagsInvalid` in the line directly below

2022-11-08 07:37 UTC, Aviv-Galmidi commented
The comments I wrote for `ACLEditor` should apply to all doc editors, just didn't want to copy paste for each file

2022-11-08 09:50 UTC, ux-AylonS commented on src/doc-editors/ACLEditor.vue
> +        this.$emit('tags-invalid', true)
because if the tags come empty without a default input 
the save button is not disabled
Although we suppose to have a default input for tags
this make sure it will not be saved empty

2022-11-08 09:56 UTC, ux-AylonS commented on src/doc-editors/ACLEditor.vue
> +        if (tags.trim() == '' || tags.length < 3) {
TagsAutoComplete state
minimumTagLength: 3,
and present the red error accordingly.
that is why I chose 3 here.

2022-11-08 10:30 UTC, Aviv-Galmidi commented on src/doc-editors/ACLEditor.vue
> +        this.$emit('tags-invalid', true)
I missed the `return` on line 232

2022-11-08 10:32 UTC, Aviv-Galmidi commented on src/doc-editors/ACLEditor.vue
> +        if (tags.trim() == '' || tags.length < 3) {
In that case, just add another `=` to the check. We usually prefer `===` over `==` as strict equality operators are considered best practice

2022-11-08 10:35 UTC, Aviv-Galmidi requested changes
Unresolved 1 comment above

https://github.com/reblaze/ui/pull/111#discussion_r1016439714

2022-11-08 10:35 UTC, Aviv-Galmidi commented on src/components/TagAutocompleteInput.vue
>        this.$emit('value-changed', this.tag)
We still emit `value-changed` instead of `tag-changed` here. Same for `value-submitted`

2022-11-09 07:33 UTC, Aviv-Galmidi requested changes
Tests are failing

2022-11-09 07:33 UTC, Aviv-Galmidi commented on src/components/__tests__/TagAutocompleteInput.spec.ts
> +    test('should bubble value-changed event as value-changed', async () => {
These tests probably fail now, as the emit from TagAutocompleteInput should be `tag-changed`

2022-11-09 07:33 UTC, Aviv-Galmidi commented on src/doc-editors/ACLEditor.vue
> +        if (tags.trim() == '' || tags.length < 3) {
```suggestion
        if (tags.trim() === '' || tags.length < 3) {
```

Strict equality operators (triple `=` as opposed to double `=`) are considered best practice, let's try to use them whenever possible

2022-11-09 07:51 UTC, ux-AylonS commented on src/components/__tests__/TagAutocompleteInput.spec.ts
> +    test('should bubble value-changed event as value-changed', async () => {
fixed

2022-11-09 08:02 UTC, Aviv-Galmidi approved these changes

2022-11-09 08:03 UTC, merged