Saas editors
reblaze/ui pull request #122
Opened 2022-11-02 10:34 UTC by ux-AylonS

Adding list of docs, New and Duplicate to 5 Editors that are. based on saasbackend server.

2022-11-03 08:40 UTC, Aviv-Galmidi requested changes
Missing MobileSDK

2022-11-03 08:40 UTC, Aviv-Galmidi commented on src/doc-editors/ConfigTemplatesEditor.vue
> +    async goToRoute(newRoute?: string) {
You never use `newRoute` in any of these functions, let's remove it if it's not needed

2022-11-03 08:40 UTC, Aviv-Galmidi commented on src/doc-editors/ConfigTemplatesEditor.vue
> +    async loadDocs(skipDocSelection?: boolean) {
You never use `skipDocSelection` in any of these functions, let's remove it if it is not needed

2022-11-03 08:51 UTC, Aviv-Galmidi commented
In addition, the unit tests are failing

2022-11-03 08:57 UTC, Aviv-Galmidi commented
One more thing: Duplicate in Dynamic Rules doesn’t duplicate action or tags, it should do so

2022-11-06 07:34 UTC, Aviv-Galmidi requested changes

2022-11-06 07:34 UTC, Aviv-Galmidi commented on src/components/__tests__/RbzTable.spec.ts
> +      const secondHeader = wrapper.findAll('.column-title').at(4)
Why did you change this to the fourth header?

2022-11-06 07:34 UTC, Aviv-Galmidi commented on src/types/index.d.ts
> -    displayFunction?: (item: any) => string | number // Will be rendered as HTML
`displayFunction` can return a `number`. That part is correct

2022-11-06 07:34 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +      return this.selectedDocID && this.selectedDocID.startsWith('dr_')
```suggestion
      return this.selectedDocID?.startsWith('dr_')
```

2022-11-06 07:34 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +      this.selectedDocID = this.docIdFromRoute
We don't need both, it's redundant. Use just `this.selectedDocID`

2022-11-06 07:34 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +      this.docIdNames = _.sortBy(_.map(this.docs, (doc) => [doc.id, doc.name]), (entry) => entry[1].toLowerCase())
Please take the new sort function from `DocumentEditor.vue`

2022-11-06 07:34 UTC, Aviv-Galmidi commented on src/doc-editors/CustomResponsesEditor.vue
> +                                      @tag-changed="selectedDocTags= $event"
Undo deleting the space

2022-11-06 07:43 UTC, ux-AylonS commented on src/types/index.d.ts
> -    displayFunction?: (item: any) => string | number // Will be rendered as HTML
string | number gives a type error
I checked that the displayFunction converting the number to string to avoid a problem

2022-11-06 10:31 UTC, ux-AylonS commented
> In addition, the unit tests are failing

fixed

2022-11-06 13:19 UTC, Aviv-Galmidi requested changes

2022-11-06 13:19 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +            const response = await getResponse()
What's the reason behind creating a new function for the sendRequest instead of leaving it as it was?

2022-11-06 13:19 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +            const url = `configs/${this.selectedBranch}/d/globalfilters/e/dr_${this.selectedDocID}/`
You can use `val` here as it was, as `val` is `selectedDocID` inside the watch

2022-11-06 13:19 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +      if (this.selectedDoc && Object.keys(this.selectedDoc).length === 2 || this.isForkLoading) {
I don't understand this change
You mix AND `&&` and OR `||` here, which should be done in parentheses `()` when possible to avoid unexpected operators precedence

Why do we need to check if fork is loading before loading the additional data for the selectedDoc?

2022-11-06 13:19 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +      if (this.docIdNames && this.docIdNames.length && this.docIdNames[0].id && !this.isReblazeDocument) {
If it's a reblazeDocument we don't need to load the document data? That does not sound right, what is this change trying to solve/achieve?

2022-11-06 13:19 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +          return idName[0] === this.selectedDocID
`docIdNames` was changed to hold `basicDocument[]` instead of `[string, string][]` - The `[string, string][]` is confusing for no reason when we have an actual type for these objects

2022-11-06 13:19 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +        this.selectedDocMatchingGlobalFilter.active = (docToAdd as DynamicRule).active // (this.selectedDoc as DynamicRule).active
What's the comment about `// (this.selectedDoc as DynamicRule).active`

2022-11-06 13:19 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +        this.selectedDocID = docToAdd.id
Why do we need it here? We change the `selectedDocID` inside `addNewDoc` this seems redundent

2022-11-06 13:19 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +.rbz-table > td {
This would not work.

Our `<td>` elements are not directly under `.rbz-table` but inside `<tbody><tr>`

Why was this change needed?

2022-11-06 14:27 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +            const response = await getResponse()
in order to utilize the await function,
without it would go into a loop without showing the data on the screen.

2022-11-06 14:51 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +      if (this.selectedDoc && Object.keys(this.selectedDoc).length === 2 || this.isForkLoading) {
this helps to present the correct data from the duplicated document.
but it belongs in watch selectedDocId line 294

2022-11-06 15:01 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +      if (this.docIdNames && this.docIdNames.length && this.docIdNames[0].id && !this.isReblazeDocument) {
OK! you are right ! it does work without it.

2022-11-06 15:23 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +        this.selectedDocMatchingGlobalFilter.active = (docToAdd as DynamicRule).active // (this.selectedDoc as DynamicRule).active
how it was before

2022-11-06 15:31 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +        this.selectedDocID = docToAdd.id
but it helps to keep and present the duplicated data: tags and actions for dynamic rules.
without it it present factory data while it save the duplicated data in the background.
by changing the selectedDocID we activate the watch that takes care of the presentation.

2022-11-06 15:34 UTC, ux-AylonS commented on src/components/RbzTable.vue
> +.rbz-table > td {
some tests were failing. but they dont any more. even with original code. removed.

2022-11-07 08:45 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +            const response = await getResponse()
This code shouldn't act differently than the following code
`const response = await RequestsUtils.sendRequest({methodName: 'GET', url})`

2022-11-07 08:46 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +        this.selectedDocMatchingGlobalFilter.active = (docToAdd as DynamicRule).active // (this.selectedDoc as DynamicRule).active
But why do we need it in a comment? Can we remove this commented code?

2022-11-07 08:54 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +        this.selectedDocID = docToAdd.id
These seems like duplicated code, we reassign selectedDocID a few lines after this one, this should happen instantly


```forkDoc
if (this.selectedDocType === 'dynamic-rules') {
        this.selectedDocID = docToAdd.id
        ...
      }
      ...
      await this.addNewDoc(docToAdd, successMessage, failureMessage)
```

Nothing in the `...` has a long process time or await

```addNewDoc
      this.setLoadingDocStatus(true)
      this.isNewLoading = true
      ...
      this.selectedDocID = docToAdd.id
```

Again, nothing in the `...` has a long process time or await


The line `this.selectedDocID = docToAdd.id` inside `addNewDoc` function should happen in a fraction of a second after the one you added in `forkDoc`, are you sure it's necessary?

2022-11-07 08:55 UTC, Aviv-Galmidi requested changes

2022-11-07 08:55 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +        if (!skipDocSelection || !_.find(this.docIdNames, (doc: {id: Document['id'], name: Document['name']}) => {
doc's type is just `Document`, no need to give it a special unique type here

2022-11-07 08:56 UTC, Aviv-Galmidi commented
Unresolved two comments above

https://github.com/reblaze/ui/pull/122#discussion_r1014826429

https://github.com/reblaze/ui/pull/122#discussion_r1014828459

2022-11-08 09:32 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +            const response = await getResponse()
OK, it works fine now.

2022-11-08 10:28 UTC, Aviv-Galmidi commented
We're missing the loading indicator in the new pages. Notice in the videos how the data displayed in the page content doesn't match the data in the dropdown on new and duplicate for a fraction of a second while we're loading the new actual data, in that time we should display a loading indicator like in DocumentEditor.vue

Without loading indicator

https://user-images.githubusercontent.com/10487148/200540815-19149c4c-9749-4566-86b9-f25d7aeebc08.mov

With loading indicator

https://user-images.githubusercontent.com/10487148/200540863-b0ed3a90-5f92-4aee-9b80-7039b24a5c5e.mov

2022-11-08 15:59 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +          <!--display correct message by priority (Document type -> Document)-->
We don't need this comment anymore, we only have a single level error now

2022-11-08 15:59 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +          <span v-if="!docs.find((doc) => doc.id.includes(selectedBackendService?.id))">
We can simplify that check by checking `selectedBackendService` directly
```suggestion
          <span v-if="!selectedBackendService?.id">
```

2022-11-08 15:59 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +    <div class="content no-data-wrapper" v-if="loadingDocCounter || !selectedBranch || !selectedBackendService">
We also need to wrap the top section with a similar check - if !loadingDocCounter. Otherwise we'll present both the content and the loading indicator at the same time instead of just one or the other

2022-11-09 09:34 UTC, Aviv-Galmidi requested changes
Apply the change to all matching `v-if`s

2022-11-09 09:34 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +         v-if="loadingDocCounter==0 && selectedBranch && selectedBackendService">
```suggestion
         v-if="!loadingDocCounter && selectedBranch && selectedBackendService">
```

0 is falsy, so we can simplify the check

2022-11-09 10:42 UTC, Aviv-Galmidi approved these changes

2022-11-09 13:10 UTC, merged