changing table classes for QuarantinedList
reblaze/ui pull request #127
Opened 2022-11-09 10:59 UTC by ux-AylonS

Signed-off-by: AylonS <aylons@reblaze.com>

2022-11-13 09:38 UTC, Aviv-Galmidi requested changes
1. When the table has no data, we should set the title checkbox to false instead of true
2. The widths are still a bit odd when on a small monitor
    a. Let's add `width: calc(100% - 220px);` to the right-side column in `MainComponent.vue` (through a class)
    b. Adjust the Quarantined columnd widths to match the system's card width. Note that the card content has some padding we should follow as well. From what I can see we need to remove 60px total. Perhaps 20px from Tags, 20px from Key Parameter, and 20px from Dynamic Rule?

2022-11-13 09:38 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> +        this.dynamicRulesNames = _.map(response.data, (rule) => {
This throws an error if response isn't status 200 with data (e.g. server is down)
Also, the loading will stop even if the request is still running, as `this.setLoadingDocStatus(false)` happens regardless of the prmoise's state

Let's change the promise `then` to async await and add an optional chaining to `response.data`

2022-11-13 09:43 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> -          classes: 'width-130px white-space-pre',
The tags column need both `vertical-scroll` and `white-space-pre` - otherwise `\n` won't create a new line

2022-11-14 07:17 UTC, ux-AylonS commented on src/components/QuarantinedList.vue
> +      return this.branchesStore.selectedBranchId || 'prod'
I was getting undefined with the corrupted database before

2022-11-14 07:34 UTC, Aviv-Galmidi requested changes

2022-11-14 07:34 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> +      // .then((response: AxiosResponse<DynamicRule[]>) => {
Remove commented out code

2022-11-14 07:34 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> +      this.dynamicRulesNames = _.map(response.data, (rule) => {
Wrap this in an `if` statement - make sure we have response.data or otherwise this function will throw errors

2022-11-14 08:16 UTC, Aviv-Galmidi requested changes

2022-11-14 08:16 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> +      if (response.data && response.data.length > 0) {
```suggestion
      if (response?.data?.length) {
```

2022-11-14 08:16 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +                      :checked="(selectedArray.length === dataArrayDisplay.length) && dataArrayDisplay.length > 0"
```suggestion
                      :checked="(selectedArray.length === dataArrayDisplay.length) && dataArrayDisplay.length"
```

2022-11-14 08:16 UTC, Aviv-Galmidi commented on src/views/MainComponent.vue
> +        <div class="column width-200">
```suggestion
        <div class="column router-view-column">
```

2022-11-14 08:16 UTC, Aviv-Galmidi commented on src/views/MainComponent.vue
>          <div class="column width-220px">
```suggestion
        <div class="column side-menu-column">
```

2022-11-14 08:16 UTC, Aviv-Galmidi commented on src/views/MainComponent.vue
> +}
These changes are so that we'll have a single source where we define the side menu width, while the main content width (router view) is defined according to the side menu width - changing the side menu width should directly affect the main content
In addition, changed the name to be more informative


```suggestion
$side-menu-width: 220px;
$router-view-width: calc(100% - #{$side-menu-width});

.side-menu-column {
  max-width: $side-menu-width;
  min-width: $side-menu-width;
  width: $side-menu-width;
}

.router-view-column {
  max-width: $router-view-width;
  min-width: $router-view-width;
  width: $router-view-width;
}
```

2022-11-14 08:16 UTC, Aviv-Galmidi commented on src/components/QuarantinedList.vue
> +          classes: 'vertical-scroll ellipsis width-100px white-space-pre',
Was these two enough? Do we not need to remove another 20px? I suggested Dynamic Rule column if we do need to do so

2022-11-14 08:22 UTC, ux-AylonS commented on src/components/RbzTable.vue
> +                      :checked="(selectedArray.length === dataArrayDisplay.length) && dataArrayDisplay.length > 0"
&& !!dataArrayDisplay.length

2022-11-14 08:36 UTC, ux-AylonS commented on src/components/QuarantinedList.vue
> +          classes: 'vertical-scroll ellipsis width-100px white-space-pre',
It looks fine.

2022-11-14 09:27 UTC, Aviv-Galmidi approved these changes

2022-11-14 09:32 UTC, merged