Premium page
reblaze/ui pull request #130
Opened 2022-11-16 11:58 UTC by ux-AylonS

new 
DynamicRulesEditor, 
DynamicRulesList, 
EdgeFunctionsList, 
EdgeFunctionsEditor, 
Premium page, 
route guard

2022-11-16 17:00 UTC, Aviv-Galmidi requested changes

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/components/SideMenu.vue
> +          external: true,
Premium is not an external link
```suggestion
```

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/router/index.ts
> +async function premiumServerIsLive(to: any, from: any) {
Looks like we're not using `to` and `from` in this funciton
```suggestion
async function premiumServerIsLive() {
```

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/router/index.ts
> +      console.log('Error while attempting to load documents')
Wrong log message
```suggestion
      console.log('Reblaze server not found, redirecting to Premium info page')
```

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/router/index.ts
> +      isLive = false
Can be removed, done on line 40
```suggestion
```

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/router/index.ts
> +  let isLive = true
Can be moved entirely to line 40, not being used beforehand

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/router/index.ts
> +  isLive = response?.status === 200
```suggestion
  const isLive = response?.status === 200
```

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/router/index.ts
> +    console.log('premium')
We're already logging the failed health check on line 36, we can keep one or the other
```suggestion
```

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/doc-editors/EdgeFunctionsEditor.vue
>      localDoc(): EdgeFunction {
localDoc not being used anywhere

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +    selectedProxyTemplate: {
Why do we need to watch this value instead of having it set a computed value similar to DocumentEditor?
It might cause issues of having different values in `this.docs` vs `selectedProxyTemplate`

Same for all other editors

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> -          this.loadCustomResponses()
Do we not need to load custom responses anymore? Might cause an issue in the table

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/views/EdgeFunctionsList.vue
> +    sortDocs() {
Why do we need to sort docs in the list page?

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/views/PremiumPage.vue
> +      </p>
```suggestion
      <p>The feature you attempted to access is not enabled for the open source version and requires the premium version.
       Please contact Reblaze in order to upgrade your subscription and receive access to the premiun features.
      </p>
```

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/views/PremiumPage.vue
> +      <p>Phone: 123-1233-1231</p>
Let's remove these until we have actual information to put in
```suggestion
```

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/views/PremiumPage.vue
> +  },
We can remove the inner config if it's not used
```suggestion
```

2022-11-16 17:00 UTC, Aviv-Galmidi commented on src/views/PremiumPage.vue
> +</style>
We can drop the `<style>` tag if it's not being used
```suggestion
```

2022-11-17 08:38 UTC, ux-AylonS commented on src/views/EdgeFunctionsList.vue
> +    sortDocs() {
isn't it better to sort them before displaying?

2022-11-17 13:17 UTC, Aviv-Galmidi commented on src/views/EdgeFunctionsList.vue
> +    sortDocs() {
We're running sort inside RbzTable based on column sort + direction + filter, so this sort doesn't matter

2022-11-17 13:38 UTC, Aviv-Galmidi commented
Jest is failing

2022-11-17 14:23 UTC, ux-AylonS commented on src/views/EdgeFunctionsList.vue
> +    sortDocs() {
I thought it influence the list in the drop down

2022-11-18 07:02 UTC, ux-AylonS commented
> 
jest is failing due to pinia
skip for now

2022-11-18 08:15 UTC, Aviv-Galmidi requested changes

2022-11-18 08:15 UTC, Aviv-Galmidi commented on src/assets/styles/main.scss
> +.name-table {
We don't need this class, can be removed

The issue with RbzTable expanding more than it should is solved elsewhere, I added it to Avihay's branch

2022-11-18 08:15 UTC, Aviv-Galmidi commented on src/assets/styles/main.scss
> +.docs-selection {
```suggestion
.doc-selection-wrapper {
```

2022-11-18 08:15 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +                   :data="dynamicRulesData"
What's the intention behind adding `:data` to the div element?

2022-11-18 08:15 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +         v-if="loadingDocCounter || !selectedBranch || !selectedBranch || !globalFiltersData">
Duplicated `!selectedBranch` check
```suggestion
         v-if="loadingDocCounter || !selectedBranch || !globalFiltersData">
```

2022-11-18 08:15 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +// import {AxiosResponse} from 'axios'CustomResponse
Remove if not needed

2022-11-18 08:15 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +            return matchingGlobalFilter?.action || 'X'
`X`? Why?

2022-11-18 08:15 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +          classes: 'width-100px min-height-40 vertical-scroll white-space-pre ellipsis',
We set a limit to all tables in the list pages to display only 1 line of text per row for a reason, we want the entire table to fit inside the monitor on first load and not have the user scroll to see the full details of the page

2022-11-19 18:07 UTC, ux-AylonS commented on src/views/DynamicRulesList.vue
> +            return matchingGlobalFilter?.action || 'X'
oops...!

2022-11-19 18:10 UTC, ux-AylonS commented on src/views/DynamicRulesList.vue
> -    loadCustomResponses() {
we bring the custom response from globalfilters directly.
it only at the editor that we need to bring all actions from custom response. right?

2022-11-20 09:34 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> -    loadCustomResponses() {
I believe the Custom Responses column will be empty after this change
We use this array to map the IDs we get from the Global Fitler to the name of the Custom Response

2022-11-20 10:47 UTC, Aviv-Galmidi approved these changes

2022-11-20 11:33 UTC, merged