Trusted nets
reblaze/ui pull request #132
Opened 2022-11-18 08:39 UTC by ux-AylonS

2022-11-18 22:19 UTC, Aviv-Galmidi requested changes

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +    showSecondButtonRow: Boolean,
That's incorrect
We're showing a second row-button (button of a row) not a second button row (row of buttons)

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
>               :class="{ collapsed: isTrustedCollapsed }">
`isTrustedCollapsed` -> `isTrustedSourcesCollapsed`

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +              />
Fix spacing and indents -
`/>` closing should be in the same line as the last property
different properties should be aligned vertically (`type`, `class`, etc.)

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +            <div class="trusted-modal-input-container ml-30"
I don't believe `ml-30` exists in bulma, `ml` usually stands for margin-left and in bulma they go from 0 to 6

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +    // openEditTrustedSource(idx: number) {
commented out on purpose?

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +      console.log('delete id', id, 'data', data)
Let's remove the console logs we don't need

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +    width: 47%;
`width: 47%` seems like a magic number, it's very specific
Can we avoid it?

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +    button {
Let's avoid editing `button` directly and give these buttons a class

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +      planetID: null,
This seems like an exessive list of new properties, and we don't use them all - for exmaple there is no call for `redis` other than this definition
Let's clean it up

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +                <button class="btn" @click="addNewTrustedSource" ><i class="fas fa-plus"></i></button>
Use bulma button classes

2022-11-18 22:19 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +                <button class="btn" @click="editTrustedSource" ><i class="fas fa-edit"></i></button>
Use bulma button classes

2022-11-19 16:55 UTC, ux-AylonS commented on src/components/RbzTable.vue
> +    showSecondButtonRow: Boolean,
well, a second button for the row
it depends where you put the comma
second button, row
second, row-button
second , button-row.

2022-11-19 17:25 UTC, ux-AylonS commented on src/doc-editors/ProxyTemplatesEditor.vue
> +    width: 47%;
it is specific for macbook screen size

2022-11-19 17:48 UTC, ux-AylonS commented on src/doc-editors/ProxyTemplatesEditor.vue
> +    width: 47%;
what would you suggest?

2022-11-20 09:00 UTC, Aviv-Galmidi requested changes

2022-11-20 09:00 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +    width: 46%;
Why exactly `46%` it's very specfic, what's the use case of these inputs? Can we use css flex / bulma columns?

2022-11-20 11:41 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplatesEditor.vue
> +                     class="input is-small ip-input data-cell is-size-7 data-cell-content ellipsis"
`data-cell` and `data-cell-content` are RbzTable classes, they won't do anything here

2022-11-21 10:25 UTC, Aviv-Galmidi commented
Moved to #135

2022-11-21 10:25 UTC, closed without merging