fix duplicate warnings in dynamic rules
reblaze/ui pull request #136
Opened 2022-11-21 10:50 UTC by ux-AylonS

Signed-off-by: AylonS <aylons@reblaze.com>

2022-11-21 10:52 UTC, ux-AylonS commented on src/doc-editors/DynamicRulesEditor.vue
> +        // const globalFilterText = this.titles['globalfilters-singular']
will delete if you confirm that we dont want to display global filter message

2022-11-21 13:34 UTC, Aviv-Galmidi commented on src/doc-editors/DynamicRulesEditor.vue
> +        // const globalFilterText = this.titles['globalfilters-singular']
We do not need to display this message

2022-11-21 20:19 UTC, Aviv-Galmidi requested changes

2022-11-21 20:19 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +          //  setSelectedDataFromRouteParams()
Why are we not calling `setSelectedDataFromRouteParams` anymore?
Repeating question for all affected files. Let's discuss

2022-11-21 20:19 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +          // this.selectedDocID = this.docIdNames[0].id
?

2022-11-21 20:38 UTC, Aviv-Galmidi commented
Jest is failing

2022-11-22 06:01 UTC, ux-AylonS commented on src/doc-editors/BackendServicesEditor.vue
> +          //  setSelectedDataFromRouteParams()
fixed for all

2022-11-22 06:07 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +          // this.selectedDocID = this.docIdNames[0].id
I cleaned it out

2022-11-22 16:24 UTC, Aviv-Galmidi requested changes

2022-11-22 16:24 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +          }
That way we're mostly removing code instead of adding more code

2022-11-22 18:50 UTC, ux-AylonS commented on src/doc-editors/DynamicRulesEditor.vue
> +                  <select
yes, my vs code started to format on save with wrong configuration.
this might be the cause.

2022-11-22 19:01 UTC, ux-AylonS commented on src/doc-editors/DynamicRulesEditor.vue
> +      docs: ([] as unknown) as DynamicRule[],
yes my vs formatter did that.

2022-11-22 20:15 UTC, ux-AylonS commented on src/doc-editors/BackendServicesEditor.vue
> +          }
only small difference

2022-11-23 06:55 UTC, Aviv-Galmidi commented on src/doc-editors/DynamicRulesEditor.vue
> +                  <select
Right, I forgot you mentioned it yesterday morning

2022-11-23 11:30 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +          }
What I meant was that we can get rid of this entire new codeblock, as we already have this check in `loadDocs`

```
          // selectedDocIndex modified with redirect
          let idx = 0
          if (this.selectedDocID) {
            idx = _.findIndex(this.docs, (doc) => {
              return doc.id === this.selectedDocID
            })
          }
          // redirect to list if no data found
          if (idx >= 0) {
            return idx
          } else {
            this.redirectToList()
          }
```

2022-11-23 11:32 UTC, Aviv-Galmidi commented on src/doc-editors/ServerGroupsEditor.vue
> +      console.log('polic', this.securityPolicies)
remove

2022-11-24 14:29 UTC, Aviv-Galmidi approved these changes

2022-11-24 14:41 UTC, Aviv-Galmidi approved these changes

2022-11-24 14:45 UTC, merged