Ssl migration
reblaze/ui pull request #142
Opened 2022-11-24 15:35 UTC by AvihayMReblaze

2022-11-24 17:19 UTC, Aviv-Galmidi requested changes
Need to clean the code from the weird vscode formatting
`CertificateEditor.vue` can be removed

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +          <div class="content">
We can remove this internal card

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +  emits: ['generate-shown-changed', 'call-load-certificate', 'delete-shown-changed', 'second-rowbutton-clicked'],
We don't need the `emits` here as this component doesn't emit anything, it only listens to other emits
```suggestion
```

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +      isDownloadLoading: false,
Not being used anywhere

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +          isSortable: true,
Probably shouldn't be sortable, these values are not linear

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +          isSortable: true,
Probably shouldn't be sortable, these values are not linear

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +          isSortable: true,
Probably shouldn't be sortable, these values are not linear

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +              return `${item?.certificates?.length + defaultCertificateNumber}/25`
What's this `/25`?

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +              return `${item?.certificates?.length + defaultCertificateNumber}/15`
What's this `/15`?

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +          }, */
Remove if not used
```suggestion
```

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +    getBalancerByID() {
computed value names usually should not start with `get` - `selectedLoadBalancerID` perhaps?

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +      return `${apiPrefix}/reblaze/configs/${this.selectedBranch}/d/ssl/`
Wrong path, it's `/certificates/` I think?

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +    },
I think this part can be removed

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +    },
Can be removed, if needed we can use the one in utils

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +      this.isNewLoading = true
You're using `this.isNewLoading` for all kind of methods here, probably meant to use `setLoadingDocStatus`?

2022-11-24 17:19 UTC, Aviv-Galmidi commented on src/views/SslList.vue
> +<style lang="scss">
```suggestion
<style scoped lang="scss">
```

We don't want to accidently affect other pages

2022-11-27 18:50 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +          <div class="content">
Done

2022-11-27 18:50 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +  emits: ['generate-shown-changed', 'call-load-certificate', 'delete-shown-changed', 'second-rowbutton-clicked'],
Done

2022-11-27 18:51 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +      isDownloadLoading: false,
Need more instructions

2022-11-27 18:51 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +          isSortable: true,
On which column?

2022-11-27 18:52 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +          isSortable: true,
On which column?

2022-11-27 18:52 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +          isSortable: true,
On which column?

2022-11-27 18:53 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +              return `${item?.certificates?.length + defaultCertificateNumber}/25`
As Shai says to me, Let's talk on that

2022-11-27 18:53 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +              return `${item?.certificates?.length + defaultCertificateNumber}/15`
^^

2022-11-27 18:55 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +    getBalancerByID() {
Done

2022-11-27 18:56 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +    },
Done

2022-11-27 18:56 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +<style lang="scss">
Done

2022-11-28 05:59 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +          }, */
Done

2022-11-28 06:15 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +      return `${apiPrefix}/reblaze/configs/${this.selectedBranch}/d/ssl/`
Let's talk about that

2022-11-28 06:15 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +    },
Done

2022-11-28 07:28 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +      this.isNewLoading = true
Done

2022-11-28 08:53 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +      isDownloadLoading: false,
Done with cleaning more variables that is unused

2022-11-28 08:53 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +          isSortable: true,
Done

2022-11-28 08:54 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +          isSortable: true,
Done

2022-11-29 13:45 UTC, AvihayMReblaze commented on src/views/SslList.vue
> +      return `${apiPrefix}/reblaze/configs/${this.selectedBranch}/d/ssl/`
Done

2022-11-29 14:22 UTC, closed without merging