Publish History page
reblaze/ui pull request #163
Opened 2022-12-02 08:10 UTC by ux-AylonS

2022-12-04 09:47 UTC, Aviv-Galmidi requested changes

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +            <div :class="col?.cellContentClasses?.includes('multi-line') ? col.cellContentClasses :
What is this change? I don't understand why we need a specific handler for `multi-line` as it's not a sepcific usecase of `cellContentClasses`

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +// import DatasetsUtils from '@/assets/DatasetsUtils'
Remove unused code

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +
Remove whitepsace
```suggestion
```

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +    async savePublishHistory() {
As stated in the ticket, this should be done inside the confserver in order to accomidate publishing done through the API

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +          fieldNames: ['full_date'],
Field name can be `date`

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +          classes: 'ellipsis width-170px',
No need for ellipsis, we know the maximum length of this cell - note that it has changed in `main` branch already so pull from main and now 140px should be enough

```suggestion
          classes: 'width-140px',
```

After this change please make sure the data is displayed without issues

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +          classes: 'width-130px',
```suggestion
          classes: 'width-130px',
          cellContentClasses: 'ellipsis',
```

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +          classes: 'ellipsis',
```suggestion
          cellContentClasses: 'ellipsis',
```

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +          classes: 'ellipsis width-170px',
```suggestion
          classes: 'width-170px',
          cellContentClasses: 'ellipsis',
```

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +          title: 'Full Date',
Title can be just `Date`
```suggestion
          title: 'Date',
```

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +          title: 'Published User',
`Author` would fit better here as it is the correct git term
```suggestion
          title: 'Author',
```

2022-12-04 09:47 UTC, Aviv-Galmidi commented on src/views/Publish.vue
> +.publish-history {
Using these margins we now have a different indents for `Publish History` and `Version History`
Simply adding `mb-5` to the same element that has `publish-history` instead of manually setting these margins should be enough

2022-12-04 09:52 UTC, ux-AylonS commented on src/components/RbzTable.vue
> +            <div :class="col?.cellContentClasses?.includes('multi-line') ? col.cellContentClasses :
there is a conflict between data-cell-content and multi-line
which is unique, only the dns-page.
This is how I alternate between the two.

2023-01-26 08:41 UTC, Aviv-Galmidi commented
Closed until further development is done

2023-01-26 08:41 UTC, closed without merging