Sso settings
reblaze/ui pull request #194
Opened 2023-02-13 10:14 UTC by AvihayMReblaze

2023-02-14 08:27 UTC, Aviv-Galmidi requested changes

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/types/index.d.ts
> +    roles_claim_key?: ''
The type should be a string, not ''

```suggestion
    roles_claim_key?: string
```

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +          <div class="columns columns-divided"  v-if="ssoData">
Break attributes into multiple lines

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                        @change="changeShown">
Let's call this `toggleEnabled` instead
Toggle as the function only toggles values (true<->false)
Enabled as the function affects the enabled value, not shown value

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                        data-qa="switch-branch-dropdown"
Wrong value

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                         data-qa="title-input"
Wrong value

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                        data-qa="switch-branch-dropdown"
Wrong value

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                        @change="protocolSelector($event)">
Let's use `switchProtocol` to stay aligned with other `<select>` elements `@change` event

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                        @change="protocolSelector($event)">
We don't need to send the `$event` in this function, we can use the value of `ssoData.protocol` inside the function directly. See: switchDocID

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                     class="card threshold-card">
Wrong class name, it's not `threshold-card`

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                             data-qa="ratelimit-limit-input"
Wrong value

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                             title="Number of events"
Wrong value

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                          <option v-for="groupName in groupNames"
We need to display user-friendly name instead of actual group names. e.g. `reblaze-events-viewer` should be something like `Events Viewer` or something else matching Reblaze v2's naming convention

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +                   :class="!ssoData.enabled? 'is-text is-small is-size-7 ml-3 add-role-button disable-new-role': 'is-text is-small is-size-7 ml-3 add-role-button'"
Most of these classes can be in `class`, no need to set them in `:class` in both true/false scenarios

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +              <div v-if="showOAuth2 === true && showSaml2 === false">
Can we use ssoData.protocol instead of `showOAuth2` and `showSaml2`?

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +              <div v-else-if="showOAuth2 === false && showSaml2 === true">
Can we use ssoData.protocol instead of `showOAuth2` and `showSaml2`?

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +      provider: provider,
It's a list of providers, not a single provider

```suggestion
      providers: providers,
```

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +    const provider = ['azure', 'okta']
It's a list of providers, not a single provider

```suggestion
    const providers = ['azure', 'okta']
```

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +    const protocol = ['oauth2', 'saml2']
It's a list of protocols, not a single protocol

```suggestion
    const protocols = ['oauth2', 'saml2']
```

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +      protocol: protocol,
It's a list of protocols, not a single protocol

```suggestion
      protocols: protocols,
```

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +      tokenExpiration: 0,
Can be removed, not used anywhere
```suggestion
```

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +      threshold: 0,
Can be removed, not used anywhere

```suggestion
```

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +      }
We don't need to add every attribute to the object when normalizing it, simply adding objects and mandatory attributes would suffice

```suggestion
      const basicSso: Sso = {
        enabled: false,
        title: '',
        provider: 'okta',
        protocol: 'oauth2',
        roles: [],
        params: {},
      }
```

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +    color: #363636;
Move color to `colors.scss`

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +  .seconds-suffix {
This already exists in `main.scss`

2023-02-14 08:27 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +  .field {
Why are we changing `field`'s design in this editor? It would look different than all other classes in the system as it's a shared class

2023-02-15 14:24 UTC, AvihayMReblaze commented on src/types/index.d.ts
> +    roles_claim_key?: ''
Done

2023-02-15 14:25 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                        @change="changeShown">
Done

2023-02-15 14:26 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                        data-qa="switch-branch-dropdown"
Done

2023-02-15 14:27 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +          <div class="columns columns-divided"  v-if="ssoData">
Done

2023-02-15 14:28 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                        data-qa="switch-branch-dropdown"
Done

2023-02-15 14:39 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                        @change="protocolSelector($event)">
Done

2023-02-15 14:40 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                        @change="protocolSelector($event)">
Done

2023-02-15 14:41 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                     class="card threshold-card">
Done, renamed it to roles-card

2023-02-15 14:42 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                             data-qa="ratelimit-limit-input"
Done

2023-02-15 14:43 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                             title="Number of events"
Same as the previous one

2023-02-15 14:54 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                        class="remove-threshold-option-button button is-light is-small remove-icon"
Renamed it as remove-threshold-option-button

2023-02-15 16:23 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +              <div v-if="showOAuth2 === true && showSaml2 === false">
I did it bit different, now it look like
v-if="ssoData.protocol === 'oauth2' ? showOAuth2 = true : showOAuth2 = false"

2023-02-15 16:24 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +              <div v-else-if="showOAuth2 === false && showSaml2 === true">
I did it bit different, now it look like
v-if="ssoData.protocol === 'oauth2' ? showOAuth2 = true : showOAuth2 = false"

2023-02-15 16:26 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +      provider: provider,
Done

2023-02-15 16:26 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +    const provider = ['azure', 'okta']
Done

2023-02-15 16:27 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +    const protocol = ['oauth2', 'saml2']
Done

2023-02-15 16:27 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +      protocol: protocol,
Done

2023-02-15 16:27 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +      tokenExpiration: 0,
Did that

2023-02-15 16:28 UTC, AvihayMReblaze commented on src/router/index.ts
> +            name: 'Sso',
Done

2023-02-15 16:30 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +      }
Done

2023-02-15 16:38 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +  .seconds-suffix {
Done, removed

2023-02-15 17:38 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +    color: #363636;
Done

2023-02-15 17:40 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +          this.setLoadingDocStatus(true)
Done

2023-02-15 17:42 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                   :class="!ssoData.enabled? 'is-text is-small is-size-7 ml-3 add-role-button disable-new-role': 'is-text is-small is-size-7 ml-3 add-role-button'"
Done

2023-02-15 17:42 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                   :class="!ssoData.enabled? 'is-text is-small is-size-7 ml-3 add-role-button disable-new-role': 'is-text is-small is-size-7 ml-3 add-role-button'"
Done

2023-02-15 18:09 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +  .field {
Fixed, done.

2023-02-16 07:08 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                         data-qa="title-input"
Done

2023-02-16 08:46 UTC, AvihayMReblaze commented on src/router/index.ts
> +            name: 'Sso',
Done

2023-02-22 13:37 UTC, AvihayMReblaze commented on src/components/SideMenu.vue
> +          disabled: !this.userStore.checkAccessLevel(this.userStore.accessLevels.reblazeUser),
Done

2023-02-22 13:38 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +                          <option v-for="groupName in groupNames"
Done

2023-02-22 13:40 UTC, Aviv-Galmidi requested changes

2023-02-22 13:46 UTC, AvihayMReblaze commented on src/stores/userStore.ts
>      ],
Done

2023-02-22 13:50 UTC, Aviv-Galmidi commented on src/stores/userStore.ts
> +    reblazeAdmin:accessLevelReblazeAdmin,
```suggestion
    reblazeAdmin: accessLevelReblazeAdmin,
```

2023-02-22 13:57 UTC, merged