User management list
reblaze/ui pull request #197
Opened 2023-02-22 13:34 UTC by AvihayMReblaze

2023-02-22 14:30 UTC, Aviv-Galmidi requested changes

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/types/index.d.ts
> +  }
I don't really like the fact that we have a users type that contain an attribute called users, I don't have an idea for a better name at the moment though

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +    documentListAPIPath(): string {
Not the correct name

usersListAPIPath?

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +                            {{ newUser.org_id? 'Select organization': 'Select organization' }}
Both options are the same, so we can just write `Select organization`

```suggestion
                            Select organization
```

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +                    <option v-for="organizationName in unionOrganizationsData"
`organizationName` sould be `organization`

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +                        @click="saveRequestNewUser">
We also need to reset `this.newUser` both in save and in cancel functions. Otherwise adding a new user, saving/cancelling and adding another user will result in the 2nd user having the values we preivously had

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +            }
Let's read these names from `accessLevels` above, instead of keeping two sources of truths telling us that 1 is Viewer, and so on

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +      isLoading: false,
Can we use `setLoadingDocStatus` instead?

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +      organizationByName: {},
Is this used?

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +      userById: {} as User,
editUser? Can it start as null?

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +      delete this.userById.email
Can we instead nullify the value? `= null`

2023-02-22 14:30 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +</style>
Can be removed
```suggestion
```

2023-02-22 15:24 UTC, AvihayMReblaze commented on src/components/SideMenu.vue
> +          title: 'User Management',
Done

2023-02-22 15:26 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> +                            {{ newUser.org_id? 'Select organization': 'Select organization' }}
Done

2023-02-22 15:35 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> +                        @click="saveRequestNewUser">
Done

2023-02-22 15:51 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> +      isLoading: false,
Change it to be specific for every save button

2023-02-22 15:58 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> +            }
Done

2023-02-22 15:59 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> +                    <option v-for="organizationName in unionOrganizationsData"
Done

2023-02-22 16:06 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> +      delete this.userById.email
Actually yes, done

2023-02-22 16:06 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> +</style>
Done

2023-02-22 16:10 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> +      userById: {} as User,
Done

2023-02-22 16:17 UTC, AvihayMReblaze commented on src/types/index.d.ts
> +  }
Done, called Organization

2023-02-23 07:41 UTC, Aviv-Galmidi requested changes

2023-02-23 07:41 UTC, Aviv-Galmidi commented on src/types/index.d.ts
> +  type UserDetails = {
Almost identical to `type User` above. Can they be merged with an optinal `otpseed`?

2023-02-23 07:41 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> -            } else if (item.acl === '100') {
We'll need to add acl 100 to the list above as it's missing there

2023-02-23 07:41 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +            return accessLevel.title
What if the accessLevel was not found?

```suggestion
            return accessLevel?.title || ''
```

2023-02-23 07:41 UTC, Aviv-Galmidi commented on src/views/UserManagement.vue
> +      this.editUserById.email = null
We can nullify the entire object at the same time

```suggestion
      this.editUserById = null
```

2023-02-23 07:47 UTC, AvihayMReblaze commented on src/types/index.d.ts
> +  type UserDetails = {
Done

2023-02-23 07:49 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> -            } else if (item.acl === '100') {
Added

2023-02-23 07:49 UTC, AvihayMReblaze commented on src/views/UserManagement.vue
> +            return accessLevel.title
Right, added

2023-02-23 08:37 UTC, Aviv-Galmidi approved these changes

2023-02-23 08:40 UTC, merged