Bugs fix
reblaze/ui pull request #205
Opened 2023-02-28 11:17 UTC by AvihayMReblaze

2023-02-28 12:30 UTC, Aviv-Galmidi requested changes

2023-02-28 12:30 UTC, Aviv-Galmidi commented on src/doc-editors/BackendServicesEditor.vue
> +    resetValues() {
```suggestion
    resetStickyCookieName() {
```

2023-02-28 12:30 UTC, Aviv-Galmidi commented on src/doc-editors/popups/EditCertificate.vue
> +      // const email = this.userStore.getCookieEmail()
Remove

2023-03-02 08:31 UTC, AvihayMReblaze commented on src/doc-editors/BackendServicesEditor.vue
> +    resetValues() {
Done

2023-03-02 08:31 UTC, AvihayMReblaze commented on src/doc-editors/popups/EditCertificate.vue
> +      // const email = this.userStore.getCookieEmail()
Done

2023-03-02 08:52 UTC, Aviv-Galmidi approved these changes

2023-03-02 08:59 UTC, merged