V5 ga 7 tooltip
reblaze/ui pull request #208
Opened 2023-03-01 10:09 UTC by SrdjanReblaze

https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-7

2023-03-02 08:28 UTC, Aviv-Galmidi requested changes
We should use `Tooltip` rather than `ToolTip` as that's the correct English writing

Please keep the component directory flat `src/components/Tooltip.vue` or something of that fashion rather than src/components/messages/ToolTip.vue

Please add storybook story preview as well

2023-03-02 08:28 UTC, Aviv-Galmidi commented on src/components/messages/ToolTip.vue
> +    >
Please keep the closing tag in the same line as the last attribute

2023-03-02 08:28 UTC, Aviv-Galmidi commented on src/components/messages/ToolTip.vue
> +      v-if="isActive"
Please keep the first attribute line in the same line as the HTML element

2023-03-02 08:28 UTC, Aviv-Galmidi commented on src/components/messages/ToolTip.vue
> +    background: $datk-blue;
Did you mean `$color-dark-blue`?

2023-03-02 08:28 UTC, Aviv-Galmidi commented on src/assets/styles/colors.scss
> +$color-dark-blue: #050038;
The color name for #050038 is `stratos` not `dark-blue`
https://chir.ag/projects/name-that-color/#050038

2023-03-02 10:19 UTC, SrdjanReblaze commented on src/components/messages/ToolTip.vue
> +    >
please, check fresh PR update

2023-03-06 09:56 UTC, Aviv-Galmidi reviewed
Approving the code so far, awaiting story before merging

2023-03-15 08:02 UTC, Aviv-Galmidi approved these changes

2023-03-15 08:03 UTC, merged