Add toggle component and test
reblaze/ui pull request #209
Opened 2023-03-01 12:06 UTC by jiggsaw85

**Jira task:** [https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-8](https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-8)

2023-03-02 16:10 UTC, jiggsaw85 commented on src/components/form/SwitchButton.vue
> +    <span v-if="label" class="label">{{ label }}</span>
@Aviv-Galmidi All fixed per comments.

2023-03-06 09:58 UTC, Aviv-Galmidi requested changes

2023-03-06 09:58 UTC, Aviv-Galmidi commented on src/views/help/HelpAndSupport.vue
> +  },
Please remove the component usage from this page

2023-03-07 07:36 UTC, Aviv-Galmidi approved these changes

2023-03-07 07:36 UTC, Aviv-Galmidi commented
Please resolve conflicts and then we'll merge

2023-03-13 09:35 UTC, jiggsaw85 commented
Conflicts fixed.

2023-03-15 08:03 UTC, Aviv-Galmidi approved these changes

2023-03-15 08:04 UTC, merged