Add search component and test
reblaze/ui pull request #211
Opened 2023-03-01 15:30 UTC by SrdjanReblaze

2023-03-02 10:18 UTC, Aviv-Galmidi requested changes
As discussed in our meeting, the SVGs should be implemented using Material Icons instead of adding specific icons

Do we need all of these fonts? It seems like only regular is being used in the new code and then we change between weights using `font-weight`

Please keep the component directory flat `src/components/SearchField.vue` rather than `src/components/form/SearchField.vue`

Please add storybook story preview as well

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/views/MainComponent.vue
> +               <search-field
Was this done for testing? If so please remove it from the PR

The change will invalidate the entire UI

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/SearchField.vue
> +      />
Please keep the closing tag in the same line as the last attribute

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/SearchField.vue
> +        type="text"
Please keep the first attribute line in the same line as the HTML element

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/SearchField.vue
> +  <div class="input-holder" :class="disabled ? 'disabled' : ''">
Please separate each attributes by a new line

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/SearchField.vue
> +      <span v-if="isTyping" class="clear" @click="handleClear">
Please separate each attributes by a new line

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/SearchField.vue
> +        <img width="25" src="./clear.svg" alt="clear" />
Please separate each attributes by a new line

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/SearchField.vue
> +    <span v-if="errorMessage" class="error-message">{{
Please separate each attributes by a new line

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/SearchField.vue
> +    <span v-if="errorMessage" class="error-message">{{
This v-if will always return true as `errorMessage` is never falsey, it can be either
```
{
  class: 'error',
  message: 'This field is required.',
}
```
or
```
{
  class: '',
  message: '',
}
```

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/__tests__/SearchField.spec.ts
> +  let wrapper:any
```suggestion
  let wrapper: VueWrapper
```

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/SearchField.vue
> +      message: 'This field is required.',
Please add a prop to allow custom error messages for each field

2023-03-02 10:18 UTC, Aviv-Galmidi commented on src/components/form/SearchField.vue
> +  (event.target as HTMLInputElement).value
Is this needed? I believe the value of the input element is automatically assigned before @input event occurs

2023-03-06 10:01 UTC, Aviv-Galmidi requested changes

2023-03-06 10:01 UTC, Aviv-Galmidi commented on src/components/FormSearchField.vue
> +        type="text"
Please keep the first attribute line in the same line as the HTML element

2023-03-06 10:01 UTC, Aviv-Galmidi commented on src/components/FormSearchField.vue
> +  <div class="input-holder" :class="disabled ? 'disabled' : ''">
Please separate each attributes by a new line

2023-03-06 10:01 UTC, Aviv-Galmidi commented on src/components/FormSearchField.vue
> +      <svg-icon v-if="!isTyping" class="search" type="mdi" :path="searchIcon" />
Please separate each attributes by a new line

2023-03-06 10:01 UTC, Aviv-Galmidi commented on src/components/FormSearchField.vue
> +      <svg-icon v-if="isTyping" class="clear" @click="handleClear" type="mdi" :path="closeIcon" />
Please separate each attributes by a new line

2023-03-06 10:01 UTC, Aviv-Galmidi commented on src/components/FormSearchField.vue
> +    <span v-if="errorMessage" class="error-message">
Please separate each attributes by a new line

2023-04-04 11:12 UTC, ljubebiza commented
Done

2023-04-04 13:21 UTC, Aviv-Galmidi submitted a review, later dismissed

2023-04-04 13:22 UTC, Aviv-Galmidi approved these changes

2023-04-04 13:28 UTC, merged