Add button component and test
reblaze/ui pull request #215
Opened 2023-03-02 15:59 UTC by jiggsaw85

**Jira task:** [https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-19](https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-19)

2023-03-06 10:02 UTC, Aviv-Galmidi requested changes

2023-03-06 10:02 UTC, Aviv-Galmidi commented on src/components/FormButton.vue
> +    <img v-if="icon && variant !== 'negative'" width="18" :src="icon" />
Please separate each attributes by a new line

2023-03-06 10:02 UTC, Aviv-Galmidi commented on src/components/FormButton.vue
> +    <svg-icon v-if="variant === 'negative'" type="mdi" :path="mdiTrashCanOutline" size="18" />
Please separate each attributes by a new line

2023-03-06 10:02 UTC, Aviv-Galmidi commented on src/components/FormButton.vue
> +  >
Please keep the closing tag in the same line as the last attribute

2023-03-06 10:02 UTC, Aviv-Galmidi commented on src/components/FormButton.vue
> +    :disabled="disabled"
Please keep the first attribute line in the same line as the HTML element

2023-03-06 12:49 UTC, jiggsaw85 commented on src/components/FormButton.vue
> +    :disabled="disabled"
@Aviv-Galmidi All fixed and storybook added.

2023-03-08 09:18 UTC, jiggsaw85 commented
@Aviv-Galmidi I have adapted button's variations.
If you want to use icon inside the button in order to test, you can put any image url inside "icon" property in storybook. I have tested with this randomly selected image: https://www.adobe.com/express/create/media_127a4cd0c28c2753638768caf8967503d38d01e4c.jpeg?width=400&format=jpeg&optimize=medium

2023-03-08 09:21 UTC, jiggsaw85 commented
Just a quick note... Following Figma (and that is how I work), image inside all button variations is 18px width but on negative button, it is 16px width.
Also, padding-left (distance from left button side to image/icon) is set to 15px but on negative button it is 16px.

These are details I am following and do not want to change it by my own.

2023-03-15 13:18 UTC, Aviv-Galmidi requested changes
1. IMG icons

> If you want to use icon inside the button in order to test, you can put any image url inside "icon" property in storybook. I have tested with this randomly selected image: https://www.adobe.com/express/create/media_127a4cd0c28c2753638768caf8967503d38d01e4c.jpeg?width=400&format=jpeg&optimize=medium

The idea was to use SVG icons similar to the trashcan (but configurable) so let's say we want a `plus` SVG icon inside `New` button

This will also resolve your next question regarding sizes

> image inside all button variations is 18px width but on negative button, it is 16px width.

Similar to the trashcan setting a size to 16 similar to the trashcan would

2. Padding

> Also, padding-left (distance from left button side to image/icon) is set to 15px but on negative button it is 16px.

Let's set them to be both 16px to look the same

3. IMG icon alignment
Let's align the trashcan with the text inside the button

<img width="162" alt="Screen Shot 2023-03-15 at 15 17 52" src="https://user-images.githubusercontent.com/10487148/225320233-2cde2d4b-1c2e-4ed4-bff2-eab5d6e335c4.png">

2023-03-15 13:18 UTC, Aviv-Galmidi commented on src/views/help/HelpAndSupport.vue
> +  },
Please remove the buttons from this page

2023-03-29 07:27 UTC, Aviv-Galmidi requested changes

2023-03-29 07:27 UTC, Aviv-Galmidi commented on src/components/FormButton.vue
>      :class="[variant, display, icon ? 'icon' : '']">
`display` is not being set anywhere

```suggestion
    :class="[variant, icon ? 'icon' : '']">
```

2023-03-29 09:17 UTC, ljubebiza commented
I have fixed redundancy

2023-03-30 06:56 UTC, merged