V5 ga 24 snackbar
reblaze/ui pull request #216
Opened 2023-03-03 13:26 UTC by SrdjanReblaze

https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-24

2023-03-06 10:17 UTC, Aviv-Galmidi requested changes

2023-03-06 10:17 UTC, Aviv-Galmidi commented on src/components/MessagesSnackBar.vue
> +  <div v-if="isActive" class="snackbar-holder">
Please separate each attributes by a new line

2023-03-06 10:17 UTC, Aviv-Galmidi commented on src/components/MessagesSnackBar.vue
> +    <svg-icon v-if="variant=='warning'" width="20" type="mdi" :path="mdiAlert" :class="`${variant} variant-icon`" />
Please separate each attributes by a new line

2023-03-06 10:30 UTC, SrdjanReblaze commented on src/components/MessagesSnackBar.vue
> +  <div v-if="isActive" class="snackbar-holder">
Ok, sorry for code styling issues, what you are using as code formatter? I am using prettier with some custom settings to make it more similar to project code style

2023-03-15 13:46 UTC, Aviv-Galmidi commented on src/components/MessagesSnackBar.vue
> +              :path="mdiAlert"
Should this be a different icon? You set it to be the same one as the warning above

2023-03-15 13:59 UTC, Aviv-Galmidi commented on src/components/MessagesSnackBar.vue
> +              :path="mdiAlert"
Implementation

<img width="338" alt="Screen Shot 2023-03-15 at 15 59 10" src="https://user-images.githubusercontent.com/10487148/225331609-ed0d435d-e873-4f87-a235-1343c5b2de2d.png">


Design

<img width="274" alt="Screen Shot 2023-03-15 at 15 59 16" src="https://user-images.githubusercontent.com/10487148/225331670-37229446-8486-4d15-ae41-950c52ad880c.png">

2023-03-15 14:43 UTC, SrdjanReblaze commented on src/components/MessagesSnackBar.vue
> +              :path="mdiAlert"
Yes, i didn't find like it is on design on https://pictogrammers.com/library/mdi/

some suggestions?

2023-03-19 10:09 UTC, Aviv-Galmidi submitted a review, later dismissed

2023-03-19 10:18 UTC, Aviv-Galmidi approved these changes

2023-03-19 10:18 UTC, merged