Add scrollbar component, test and storybook
reblaze/ui pull request #218
Opened 2023-03-06 11:36 UTC by jiggsaw85

**Jira task:** [https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-22](https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-22)

2023-03-15 12:44 UTC, Aviv-Galmidi requested changes

2023-03-23 11:13 UTC, jiggsaw85 commented on src/components/AreaScrollbar.vue
> +    return scrollableAreaWidth
Initially, scrollable area width and height are set to "auto". They will fully adjust to width and height of the parent element. 
Properties "width" and "height" are added just for fine tuning if needed.

**For example:**
You set a div with width of 400px and then scrollable area inside. Without to set any prop on scrollable area, scroll will appear once your content pass over 400px width. It is the same case with the height.

I think it is simplest as it can be. So props width and height are optional and no need to set them.

I suggest to play around in storybook, or include component on same page and test a bit. If you insist, no problem, we can change the workflow of the component as you suggest.

2023-03-28 06:43 UTC, Aviv-Galmidi submitted a review, later dismissed

2023-03-28 06:44 UTC, Aviv-Galmidi approved these changes

2023-03-28 06:49 UTC, merged