V5 ga 9 chip
reblaze/ui pull request #225
Opened 2023-03-10 08:59 UTC by SrdjanReblaze

https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-9

2023-03-19 11:30 UTC, Aviv-Galmidi requested changes
![Screen Shot 2023-03-19 at 13 29 31](https://user-images.githubusercontent.com/10487148/226172388-25ada113-9ff4-4e57-86a6-0e896d5422d1.png)

Where did the outline come from? I cannot find it in the figma

2023-03-19 11:30 UTC, Aviv-Galmidi commented on src/components/CustomTag.vue
> +    color: $color-chalice;
This color isn't set in `colors.scss`

2023-03-19 11:30 UTC, Aviv-Galmidi commented on src/components/CustomTag.vue
> +  <div :class="[{disabled: disabled}, variant]">
The component should have a height of 20px

2023-03-20 08:19 UTC, SrdjanReblaze commented on src/components/CustomTag.vue
> +    color: $color-chalice;
updated

2023-03-28 14:33 UTC, ljubebiza commented
Outline is under fill tag in Figma

![Screenshot from 2023-03-28 16-20-25](https://user-images.githubusercontent.com/64750430/228268849-36d2b30d-34e4-4bc9-8564-7418bd6b668c.png)

I also changed sass property for close-svg from display none to visibility hidden in order to prevent tags to move around on hover if there is more than one tag. Please let me know if I should come up with another solution.

2023-03-29 07:47 UTC, Aviv-Galmidi requested changes
1. The closing icon covers the text instead of being half-transparent-half-white

```
background: #FFFFFF;
opacity: 0.6;
```

<img width="735" alt="Screen Shot 2023-03-29 at 10 44 31" src="https://user-images.githubusercontent.com/10487148/228462767-8b1d3918-7bfe-4296-894b-c3d6a8b7e97a.png">
<img width="212" alt="Screen Shot 2023-03-29 at 10 43 34" src="https://user-images.githubusercontent.com/10487148/228462776-897e21bc-946e-40cd-ba7f-8cf0070dae01.png">
<img width="211" alt="Screen Shot 2023-03-29 at 10 43 25" src="https://user-images.githubusercontent.com/10487148/228462782-1cb0d711-78b4-434f-b25f-49a05f457001.png">


2. It looks like the design is for the closing icon to enlrage the tag a little on hover or click (while displayed) and not always have the space allocated for


3. Found the border, thanks for the clarification

2023-03-30 06:58 UTC, Aviv-Galmidi approved these changes

2023-03-30 07:00 UTC, Aviv-Galmidi commented
> Thank you for directing me on right path. I have fixed everything by design. But I am still concerned because tag is not fixed size it will move other elements on page on hover.

I understand where your concern is coming form, this is the design we receieved and would like to go with. We'll keep the fact that the chips would move on hover in mind in our internal testing and get user feedback on the subject

2023-03-30 07:06 UTC, merged