Add tabs components. add test, add storybook
reblaze/ui pull request #226
Opened 2023-03-13 09:29 UTC by jiggsaw85

**Jira task**: [https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-20](https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-20)

2023-03-28 06:58 UTC, Aviv-Galmidi requested changes
Could we perhaps remove TabElement.vue and integrate it into TabsWrapper.vue inside a v-for loop running on $slots?

Something like

`
<template v-for="(slot, index) of Object.keys($slots)" :key="index" v-slot:[slot]>
    <slot :name="slot"></slot>
</template>
`

It seems kind of redundant and doesn't do anything other than v-show the inner slot

2023-04-03 11:48 UTC, ljubebiza commented
I have made something similar to your suggestion at the end, now there is only one component for tabs

2023-04-04 13:19 UTC, Aviv-Galmidi commented on src/components/TabsWrapper.vue
> +  disabled?: string;
What if we want multiple disabled tabs? Can we make this into an array of strings and check if it contains the title of the tab?

e.g. prop value `['I am disabled', 'gallery']` and then check if array includes the `tab.title` instead of equals to it

2023-04-04 17:34 UTC, Aviv-Galmidi approved these changes

2023-04-04 17:34 UTC, merged