Update surface component
reblaze/ui pull request #227
Opened 2023-03-13 10:11 UTC by jiggsaw85

**Jira task**: [https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-21](https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-21)

2023-03-19 13:25 UTC, Aviv-Galmidi requested changes

2023-03-19 13:25 UTC, Aviv-Galmidi commented on src/components/SurfaceBackground.vue
> +      height: `${height}px`,
That wouldn't work with percentile height/width or when using `auto`
Perhaps an injected class / styling or parent styling would work better here instead

2023-03-19 13:25 UTC, Aviv-Galmidi commented on src/components/SurfaceBackground.vue
> +  position: 'left',
I don't think a position is needed, we can simply position the component in the parent component where it needs to be

2023-03-23 10:42 UTC, jiggsaw85 commented on src/components/SurfaceBackground.vue
> +      height: `${height}px`,
You are right. I have set that default width and height of component will be 100% and this way, you can control it via parent element's styles.
Also, I have added optional property "width" with some width values of 75%, 50%, 30%, 25% and 20%. This will allow you some adidtional setup if needed on a component level.

2023-03-28 06:47 UTC, Aviv-Galmidi requested changes

2023-03-28 06:47 UTC, Aviv-Galmidi commented on src/components/SurfaceBackground.vue
> +  width?: SurfaceSize;
What do you think about allowing width to be a string, and populating it into the css width without any transfomration?

e.g.
prop received `auto` then css would be `width: auto`
prop received `130px` then css would be `width: 130px`

That way we'll allow all possible widths without hard coding any of them

2023-03-30 07:01 UTC, Aviv-Galmidi approved these changes

2023-03-30 07:01 UTC, merged