V5 ga 7 tooltip
reblaze/ui pull request #230
Opened 2023-03-16 09:06 UTC by SrdjanReblaze

storybook style fix

2023-03-21 11:10 UTC, Aviv-Galmidi requested changes

2023-03-21 11:10 UTC, Aviv-Galmidi commented on src/components/MessagesTooltip.vue
> +      v-if="isActive"
Please keep the first attribute in the same line as the openning element

2023-03-21 11:16 UTC, SrdjanReblaze commented on src/components/MessagesTooltip.vue
> +      v-if="isActive"
sorry, updated

2023-03-21 11:17 UTC, Aviv-Galmidi approved these changes

2023-03-22 11:15 UTC, Aviv-Galmidi approved these changes

2023-03-22 11:15 UTC, merged