Fix bugs 2978, 3021, 3016
reblaze/ui pull request #239
Opened 2023-03-23 19:57 UTC by AvihayMReblaze

2023-03-26 08:09 UTC, Aviv-Galmidi requested changes

2023-03-26 08:09 UTC, Aviv-Galmidi commented on src/views/SsoSettings.vue
> +      return `${apiPrefix}/api/v3/reblaze/tools/sso/`
`/api/v3` is already included in the root and version

```suggestion
      return `${apiPrefix}/reblaze/tools/sso/`
```

2023-03-26 13:07 UTC, AvihayMReblaze commented on src/views/SsoSettings.vue
> +      return `${apiPrefix}/api/v3/reblaze/tools/sso/`
Done

2023-03-27 07:54 UTC, Aviv-Galmidi approved these changes

2023-03-27 07:54 UTC, merged