V5 ga 19 button
reblaze/ui pull request #253
Opened 2023-04-20 13:46 UTC by ljubebiza

fix class commingling

2023-04-23 07:08 UTC, Aviv-Galmidi requested changes

2023-04-23 07:08 UTC, Aviv-Galmidi commented on src/components/FormButton.vue
> +export type IconVariant = 'outlined' | 'filed';
You're mixing two types of variants here, we have `outlined` / `rounded` / `sharp`, and the other variant is `filled` or not (Note: Filled with double `l` not a single `l`)

If we want the first variant type we whould to change the class above to
`:class="`material-symbols-${iconVariant} button-icon`"`
Which would result in `material-symbols-outlined` or `material-symbols-sharp`

If we want the second variant, we don't need `outlined` as an option here, and it could be a boolean if either filled or not

2023-05-18 08:40 UTC, Aviv-Galmidi commented
Awaiting PR fixes, outlined and filled are not the same type of variants as described in the comment above

2023-05-23 16:21 UTC, SrdjanReblaze commented
Not sure about this, can you please @Aviv-Galmidi compare this with latest ux-upgrade FormButton and see is there any changes of this needed?

2023-07-16 11:30 UTC, closed without merging