V5 ga 84 dynamic rules editor
reblaze/ui pull request #258
Opened 2023-04-24 10:08 UTC by SrdjanReblaze

all fields replaced, except automatic tag fields (missing design for that component)

![image](https://user-images.githubusercontent.com/125982820/233966613-3d7bb30e-c82a-4b6c-a709-70baba754ad9.png)

2023-04-27 12:36 UTC, Aviv-Galmidi requested changes

2023-04-27 12:36 UTC, Aviv-Galmidi commented on src/views/premium-security/DynamicRulesEditor.vue
> +      console.log(preparedOptions)
Remove console.log

2023-04-27 12:36 UTC, Aviv-Galmidi commented on src/views/premium-security/DynamicRulesEditor.vue
> +      console.log(preparedOptions)
Remove console.log

2023-04-27 12:36 UTC, Aviv-Galmidi commented on src/views/premium-security/DynamicRulesEditor.vue
> +    prepareNamesOptions() {
Can these 2 `prepare` functions be turned into computed values?

2023-05-05 11:25 UTC, SrdjanReblaze commented on src/views/premium-security/DynamicRulesEditor.vue
> +    prepareNamesOptions() {
done, made different inline solution

2023-05-05 11:25 UTC, SrdjanReblaze commented on src/views/premium-security/DynamicRulesEditor.vue
> +      console.log(preparedOptions)
done

2023-05-05 11:25 UTC, SrdjanReblaze commented on src/views/premium-security/DynamicRulesEditor.vue
> +      console.log(preparedOptions)
done

2023-05-09 11:19 UTC, Aviv-Galmidi approved these changes

2023-05-09 11:19 UTC, merged