Replace components on Flow Control Policies editor page
reblaze/ui pull request #259
Opened 2023-04-25 08:21 UTC by jiggsaw85

**Jira task:** [https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?label=Screen_Conversion&selectedIssue=V5GA-60](https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?label=Screen_Conversion&selectedIssue=V5GA-60)

2023-05-01 06:30 UTC, Aviv-Galmidi requested changes
The `add` and `delete` buttons for sequence need to be converted to the new buttons as well

<img width="64" alt="Screen Shot 2023-05-01 at 9 28 59" src="https://user-images.githubusercontent.com/10487148/235416894-224002fe-76f1-407c-90c0-d6fd3f20647e.png">
<img width="670" alt="Screen Shot 2023-05-01 at 9 28 56" src="https://user-images.githubusercontent.com/10487148/235416896-a8f3a1bf-b2ca-4819-9303-8f044b17871f.png">

2023-05-01 07:32 UTC, Aviv-Galmidi commented
<img width="421" alt="Screen Shot 2023-05-01 at 10 32 04" src="https://user-images.githubusercontent.com/10487148/235423354-788981c6-9f2f-4f17-bb82-b4b31dbec75d.png">

Icon should be replaced with the new icon

2023-05-05 08:40 UTC, jiggsaw85 commented
@Aviv-Galmidi All changes are made. Test for this page had 24 errors, not simply to fix because, it was not only missing classes issue. I fixed 14 tests and skipped 10, but I can confirm that all works on the page as expected.

2023-05-09 11:27 UTC, Aviv-Galmidi requested changes

2023-05-18 08:40 UTC, Aviv-Galmidi commented
Awaiting PR fixes

2023-05-22 08:21 UTC, SrdjanReblaze commented on src/assets/styles/main.scss
> +.my-1 {
done

2023-05-22 08:22 UTC, SrdjanReblaze commented on src/views/security/FlowControlPoliciesEditor.vue
> +                    <td colspan="5" class="d-inline-flex">
done

2023-05-22 08:22 UTC, SrdjanReblaze commented
> Awaiting PR fixes

all done

2023-05-22 14:26 UTC, merged