V5 ga 117 generate certificate
reblaze/ui pull request #262
Opened 2023-04-27 09:18 UTC by SrdjanReblaze

![Screenshot from 2023-04-27 11-02-09](https://user-images.githubusercontent.com/125982820/234817923-5c3eca46-d47e-4130-91b2-41600efc391f.png)
![Screenshot from 2023-04-27 11-01-55](https://user-images.githubusercontent.com/125982820/234817934-da7ecab0-4c72-4d91-9bce-f8c9ed999f6f.png)
![Screenshot from 2023-04-27 11-01-39](https://user-images.githubusercontent.com/125982820/234817941-01629691-8380-4e0a-b4d5-c248486e74cc.png)

https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-117

2023-05-01 07:12 UTC, Aviv-Galmidi requested changes
1. Tests need to pass

2. Modals weren't converted to the new modal component

3. Divider line `<hr>` wasn't converted to the new divider line component

4. Buttons are clamped together for new and edit modals

<img width="1440" alt="Screen Shot 2023-05-01 at 9 42 22" src="https://user-images.githubusercontent.com/10487148/235418060-83772031-20d5-403d-94d5-d97cbb72a143.png">

5. Buttons are not aligned in delete modal

<img width="679" alt="Screen Shot 2023-05-01 at 9 47 04" src="https://user-images.githubusercontent.com/10487148/235418564-b22a0026-fe99-4efa-9ef3-1b6a1053ae08.png">

6. Console errors when trying to save certificate after editing the attached apps

<img width="1428" alt="Screen Shot 2023-05-01 at 10 09 52" src="https://user-images.githubusercontent.com/10487148/235420994-bd71c143-2775-440b-b360-095adbc581be.png">

2023-05-01 07:12 UTC, Aviv-Galmidi commented on src/components/SslEditCertificate.vue
> +                         :disabled="isSaveEditDisabled"
Button is not disabled when it should be

2023-05-01 07:12 UTC, Aviv-Galmidi commented on src/components/SslGenerateCertificate.vue
> +      isManualInput: 'manual',
Let's change the name to `inputType` and the type to `'manual' | 'extract'`

2023-05-01 07:12 UTC, Aviv-Galmidi commented on src/views/premium-security/DynamicRulesEditor.vue
Added by accident?

2023-05-18 10:02 UTC, Aviv-Galmidi requested changes
Comments from previous review that were not fixed:

1. Modals weren't converted to the new modal component

2. The selected apps do not show up as selected by default
https://github.com/reblaze/ui/pull/262/#discussion_r1181426690

3. The dropdown doesn't show up when there are no items to display (placeholder expected)
https://github.com/reblaze/ui/pull/262/#discussion_r1181427920

4. Let's change the name to inputType and the type to 'manual' | 'extract'
https://github.com/reblaze/ui/pull/262/#discussion_r1181432370

New items:

5. vue.config.js needs to be reverted to the original code

6. Warning when clicking the radio button "Extract pfx file" in new form
![Screen Shot 2023-05-18 at 13 00 19](https://github.com/reblaze/ui/assets/10487148/1aa9521b-1046-4b11-8d84-a5f8f75be463)

7. Error when uploading pfx file
![Screen Shot 2023-05-18 at 13 01 09](https://github.com/reblaze/ui/assets/10487148/a22b0ee9-5566-4789-97c4-9ffc09fca244)

8. Extract password and button not aligned
![Screen Shot 2023-05-18 at 13 01 38](https://github.com/reblaze/ui/assets/10487148/a06723ac-2d3a-45d4-9f91-49f8f8ec7842)

2023-05-22 21:32 UTC, SrdjanReblaze commented
all comments fixed, please check this is most advanced conversion because of different response of multiselect dropdown

2023-05-23 12:53 UTC, Aviv-Galmidi commented
Comments from previous review that were not fixed:

* Modals weren't converted to the new modal component

* The dropdown doesn't show up when there are no items to display (placeholder expected)
`https://github.com/reblaze/ui/pull/262/#discussion_r1181427920`

* Let's change the name to inputType and the type to 'manual' | 'extract'
`https://github.com/reblaze/ui/pull/262/#discussion_r1181432370`

* Warning when clicking the radio button "Extract pfx file" in new form

![](https://user-images.githubusercontent.com/10487148/239204327-1aa9521b-1046-4b11-8d84-a5f8f75be463.png)

2023-05-23 15:22 UTC, SrdjanReblaze commented
> Comments from previous review that were not fixed:
> 
> * Modals weren't converted to the new modal component
> * The dropdown doesn't show up when there are no items to display (placeholder expected)
>   `https://github.com/reblaze/ui/pull/262/#discussion_r1181427920`
> * Let's change the name to inputType and the type to 'manual' | 'extract'
>   `https://github.com/reblaze/ui/pull/262/#discussion_r1181432370`
> * Warning when clicking the radio button "Extract pfx file" in new form
> 
> ![](https://user-images.githubusercontent.com/10487148/239204327-1aa9521b-1046-4b11-8d84-a5f8f75be463.png)

fixed, please check about inputType and no items dropdown, it looks good to me, modal conversion done for generate, edit and  delete too

2023-07-16 11:30 UTC, Aviv-Galmidi commented
Added as part of the branch `ux-upgrade-next`

2023-07-16 11:30 UTC, closed without merging