V5 ga 53 security policies editor
reblaze/ui pull request #263
Opened 2023-04-27 09:20 UTC by ljubebiza

2023-05-01 07:46 UTC, Aviv-Galmidi requested changes
Tests need to pass

2023-05-01 07:46 UTC, Aviv-Galmidi commented on src/store/UserStore.ts
> +    return !!userHasAccessLevel || !!devMode || true
Remove from PR

2023-05-01 07:46 UTC, Aviv-Galmidi commented on vue.config.js
> +        target: 'http://34.107.111.154:8911',
Remove from PR

2023-05-01 07:46 UTC, Aviv-Galmidi commented on src/views/security/SecurityPoliciesEditor.vue
> +                    <form-input data-qa="security-policies-match-input"
Match Host doesn't show data from the Security Policy



https://user-images.githubusercontent.com/10487148/235424385-59caf258-ef8a-4cee-98ef-7276a144370e.mov

2023-05-01 07:46 UTC, Aviv-Galmidi commented on src/views/security/SecurityPoliciesEditor.vue
> +                    <custom-tag v-for="(tag, index) in automaticTags"
Automatic tags flicker on hover




https://user-images.githubusercontent.com/10487148/235424447-86d57298-ff66-4de6-91f7-beadffd2f252.mov

2023-05-01 07:46 UTC, Aviv-Galmidi commented on src/views/security/SecurityPoliciesEditor.vue
>                          <div class="field">
`Fork path mapping` button was not converted

2023-05-01 07:46 UTC, Aviv-Galmidi commented on src/views/security/SecurityPoliciesEditor.vue
> +                            <form-input name="mapEntryMatch"
This input does not contain any data on startup

<img width="722" alt="Screen Shot 2023-05-01 at 10 39 35" src="https://user-images.githubusercontent.com/10487148/235424636-6dab7e66-6954-4806-baaf-bb536e91d51b.png">

2023-05-01 07:46 UTC, Aviv-Galmidi commented on src/views/security/SecurityPoliciesEditor.vue
> +                            variant="tertiary"
Should be negative

2023-05-16 10:24 UTC, SrdjanReblaze commented on src/views/security/SecurityPoliciesEditor.vue
> +                    <form-input data-qa="security-policies-match-input"
done

2023-05-16 10:26 UTC, SrdjanReblaze commented on src/views/security/SecurityPoliciesEditor.vue
> +                            <form-input name="mapEntryMatch"
done

2023-05-16 10:27 UTC, SrdjanReblaze commented on src/views/security/SecurityPoliciesEditor.vue
> +                            variant="tertiary"
done

2023-05-16 10:27 UTC, SrdjanReblaze commented on src/views/security/SecurityPoliciesEditor.vue
>                          <div class="field">
done

2023-05-18 10:11 UTC, Aviv-Galmidi requested changes
1. Delete button is messed up
![Screen Shot 2023-05-18 at 13 05 04](https://github.com/reblaze/ui/assets/10487148/a7ee75c4-9f0b-4d6e-9cda-b3a3f2a9f34d)

2. Button icon is missing
![Screen Shot 2023-05-18 at 13 08 07](https://github.com/reblaze/ui/assets/10487148/858de40e-d7f3-4186-8b8e-b495e82bfe40)

3. Table column widths changed drastically
Old
![Screen Shot 2023-05-18 at 13 08 51](https://github.com/reblaze/ui/assets/10487148/e230e465-e91f-4ff8-95fd-408f854e0b0a)
New
![Screen Shot 2023-05-18 at 13 08 46](https://github.com/reblaze/ui/assets/10487148/8da87c46-c836-4c48-8ef7-89728578f7e6)

2023-05-22 07:04 UTC, SrdjanReblaze commented
> 1. Delete button is messed up
>    ![Screen Shot 2023-05-18 at 13 05 04](https://user-images.githubusercontent.com/10487148/239205299-a7ee75c4-9f0b-4d6e-9cda-b3a3f2a9f34d.png)
> 2. Button icon is missing
>    ![Screen Shot 2023-05-18 at 13 08 07](https://user-images.githubusercontent.com/10487148/239205951-858de40e-d7f3-4186-8b8e-b495e82bfe40.png)
> 3. Table column widths changed drastically
>    Old
>    ![Screen Shot 2023-05-18 at 13 08 51](https://user-images.githubusercontent.com/10487148/239206131-e230e465-e91f-4ff8-95fd-408f854e0b0a.png)
>    New
>    ![Screen Shot 2023-05-18 at 13 08 46](https://user-images.githubusercontent.com/10487148/239206153-8da87c46-c836-4c48-8ef7-89728578f7e6.png)

done

2023-05-22 09:38 UTC, Aviv-Galmidi submitted a review, later dismissed

2023-05-22 09:49 UTC, Aviv-Galmidi approved these changes

2023-05-22 10:32 UTC, Aviv-Galmidi approved these changes

2023-05-22 10:32 UTC, merged