V5 ga 80 custom response editor
reblaze/ui pull request #266
Opened 2023-05-01 07:24 UTC by SrdjanReblaze

![image](https://user-images.githubusercontent.com/125982820/235422384-d6dc1196-419d-482a-8061-1ee4ea0632e0.png)
https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?selectedIssue=V5GA-80

2023-05-10 08:12 UTC, Aviv-Galmidi requested changes

2023-05-10 08:12 UTC, Aviv-Galmidi commented on src/views/security/CustomResponsesEditor.vue
>                    <button class="button is-light is-small remove-icon is-small has-text-grey"
Button was not converted

2023-05-10 08:12 UTC, Aviv-Galmidi commented on src/views/security/CustomResponsesEditor.vue
> +                 dataQa="add-new-key-btn"
`data-qa` is the correct format, attributes are declared as camelCase in the component but used in kebab-case when implemented in HTML
Please change in the rest of the code added in this PR

2023-05-11 07:13 UTC, SrdjanReblaze commented on src/views/security/CustomResponsesEditor.vue
>                    <button class="button is-light is-small remove-icon is-small has-text-grey"
done

2023-05-11 07:13 UTC, SrdjanReblaze commented on src/views/security/CustomResponsesEditor.vue
> +                 dataQa="add-new-key-btn"
done

2023-05-18 10:14 UTC, Aviv-Galmidi requested changes
1. Header title is duplicated for each entry of a header, we don't need this title at all as we have the `Request Headers` above it
new
![Screen Shot 2023-05-18 at 13 13 44](https://github.com/reblaze/ui/assets/10487148/0eaecf6a-08d7-4f9f-a69a-21f6a289a629)
old
![Screen Shot 2023-05-18 at 13 13 35](https://github.com/reblaze/ui/assets/10487148/d2d453b6-91ad-4350-9b99-65372be0f363)

2023-05-19 13:36 UTC, SrdjanReblaze commented
> 1. Header title is duplicated for each entry of a header, we don't need this title at all as we have the `Request Headers` above it
>    new
>    ![Screen Shot 2023-05-18 at 13 13 44](https://user-images.githubusercontent.com/10487148/239207189-0eaecf6a-08d7-4f9f-a69a-21f6a289a629.png)
>    old
>    ![Screen Shot 2023-05-18 at 13 13 35](https://user-images.githubusercontent.com/10487148/239207191-d2d453b6-91ad-4350-9b99-65372be0f363.png)

done

2023-05-22 09:29 UTC, Aviv-Galmidi approved these changes

2023-05-22 09:29 UTC, merged