V5 ga 246 sso configuration
reblaze/ui pull request #267
Opened 2023-05-01 10:10 UTC by SrdjanReblaze

![image](https://user-images.githubusercontent.com/125982820/235439058-0ad64b66-7ebd-48c7-b619-d9462084e5ff.png)

2023-05-04 07:26 UTC, Aviv-Galmidi requested changes
1. Labels do not match one another in the page, some are bold and some are not

<img width="551" alt="Screen Shot 2023-05-04 at 10 19 56" src="https://user-images.githubusercontent.com/10487148/236136541-53a84378-dd37-4fee-876d-5e29d33a9eaf.png">

2023-05-04 07:26 UTC, Aviv-Galmidi commented on src/components/FormInput.vue
> -    </span>
This is needed, please restore the icon code

2023-05-04 07:26 UTC, Aviv-Galmidi commented on src/views/integrations/SsoSettings.vue
>                      <button
Button was not converted

<img width="551" alt="Screen Shot 2023-05-04 at 10 25 19" src="https://user-images.githubusercontent.com/10487148/236137657-c84ecc46-f788-42a0-a4a2-72fe515a54db.png">

2023-05-04 07:26 UTC, Aviv-Galmidi commented on vue.config.js
> +        target: 'http://35.234.67.139:8911',
Please revert to original values

2023-05-05 10:20 UTC, SrdjanReblaze commented
> 1. Labels do not match one another in the page, some are bold and some are not
> 
> <img alt="Screen Shot 2023-05-04 at 10 19 56" width="551" src="https://user-images.githubusercontent.com/10487148/236136541-53a84378-dd37-4fee-876d-5e29d33a9eaf.png">

Yes, because on figma design there is no label for Dropdown fields, so i leave labels that was there, they are bolder

2023-05-05 10:34 UTC, SrdjanReblaze commented on src/components/FormInput.vue
> -    </span>
done

2023-05-05 10:34 UTC, SrdjanReblaze commented on vue.config.js
> +        target: 'http://35.234.67.139:8911',
done

2023-05-05 10:48 UTC, SrdjanReblaze commented on src/views/integrations/SsoSettings.vue
>                      <button
![image](https://user-images.githubusercontent.com/125982820/236438700-ccd427e8-9947-4e9f-8221-5ba133a4aeb4.png)

done

2023-05-10 07:30 UTC, Aviv-Galmidi submitted a review, later dismissed
Please fix the conflicts and then we can merge

2023-05-10 09:35 UTC, SrdjanReblaze commented
> Please fix the conflicts and then we can merge

done

2023-05-10 10:29 UTC, Aviv-Galmidi approved these changes

2023-05-10 10:29 UTC, merged