V5 ga 129 system db
reblaze/ui pull request #274
Opened 2023-05-08 15:18 UTC by jiggsaw85

**Jira task**: [https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?label=Screen_Conversion&selectedIssue=V5GA-129](https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?label=Screen_Conversion&selectedIssue=V5GA-129)

2023-05-18 11:13 UTC, Aviv-Galmidi requested changes
1. Selected namespace / key are not selected by default
New
![Screen Shot 2023-05-18 at 14 04 07](https://github.com/reblaze/ui/assets/10487148/03fcf1ad-194c-4736-bf3d-2df963a51ee8)
Old
![Screen Shot 2023-05-18 at 14 06 15](https://github.com/reblaze/ui/assets/10487148/04dfce97-b2d5-465d-a447-f1f26f596586)

2. When creating a new namespace (and I assume key) - it doesn't show up in the dropdown
![Screen Shot 2023-05-18 at 14 09 55](https://github.com/reblaze/ui/assets/10487148/5df8d191-b942-410a-90b1-fc49f836ab03)

3. Changing namespaces doesn't change the data
4. Changing keys doesn't change the data
5. Changing namespaces doesn't load the new namespace keys

3 and 4 and 5
![Screen Shot 2023-05-18 at 14 10 28](https://github.com/reblaze/ui/assets/10487148/4d859af5-d2ae-479a-86e3-fd280cec36f3)

6. Buttons need a bit wider gap between them
![Screen Shot 2023-05-18 at 14 13 01](https://github.com/reblaze/ui/assets/10487148/8146fc8b-a036-425d-b6d9-f3f7d9e3b96e)

2023-05-18 11:13 UTC, Aviv-Galmidi commented on src/assets/styles/main.scss
> +
Please use `width-100px` , `width-120px` , and `width-200px` if possible

2023-05-18 11:13 UTC, Aviv-Galmidi commented on src/components/FormButton.vue
> +.color-red {
Not used anywhere, can be removed

2023-05-22 09:22 UTC, SrdjanReblaze commented
all comments fixed

2023-05-22 12:52 UTC, Aviv-Galmidi commented
Numbers 2, 5, and 6 were not fixed yet

2023-05-22 16:29 UTC, SrdjanReblaze commented
> Numbers 2, 5, and 6 were not fixed yet

agree, sorry i typed all pr fixed accidently here, trying to solve this issue with dropdown

2023-05-23 14:08 UTC, SrdjanReblaze commented
everything fixed @Aviv-Galmidi

2023-06-27 06:41 UTC, Aviv-Galmidi commented
Merged as part of `ux-upgrade-next`

2023-06-27 06:41 UTC, closed without merging