V5 ga 89 mobile sdk editor
reblaze/ui pull request #275
Opened 2023-05-09 08:14 UTC by jiggsaw85

**Jira task:** [https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?label=Screen_Conversion&selectedIssue=V5GA-89](https://reblaze.atlassian.net/jira/software/projects/V5GA/boards/39?label=Screen_Conversion&selectedIssue=V5GA-89)

2023-05-10 09:11 UTC, Aviv-Galmidi reviewed
1. Getting errors for focus, missing ref?

![Screen Shot 2023-05-10 at 12 03 46](https://github.com/reblaze/ui/assets/10487148/16581f3b-078c-40b2-9fd3-a6e5f1007216)
![Screen Shot 2023-05-10 at 12 05 11](https://github.com/reblaze/ui/assets/10487148/fb0d258d-88d1-4c31-8f90-c8a2c08ebe4a)

2. Console is full of prop warnings when opening the page, please take a look at them

![Screen Shot 2023-05-10 at 12 06 01](https://github.com/reblaze/ui/assets/10487148/7225b888-d3f9-4bb1-8a66-2dd6765361eb)

3. Adding signature doesn't work


https://github.com/reblaze/ui/assets/10487148/331ac7d1-f70e-400a-9451-ee888ca086b0

2023-05-10 09:11 UTC, Aviv-Galmidi commented on src/assets/styles/main.scss
> +}
Please keep our style for width classes and place them at the top of the file with the rest of the width classes (in order of narrow(up)->wide(down)
```
.width-70px {
  max-width: 70px;
  min-width: 70px;
  width: 70px;
}
```

2023-05-10 09:11 UTC, Aviv-Galmidi requested changes
1. Getting errors for focus, missing ref?

![Screen Shot 2023-05-10 at 12 03 46](https://github.com/reblaze/ui/assets/10487148/16581f3b-078c-40b2-9fd3-a6e5f1007216)
![Screen Shot 2023-05-10 at 12 05 11](https://github.com/reblaze/ui/assets/10487148/fb0d258d-88d1-4c31-8f90-c8a2c08ebe4a)

2. Console is full of prop warnings when opening the page, please take a look at them

![Screen Shot 2023-05-10 at 12 06 01](https://github.com/reblaze/ui/assets/10487148/7225b888-d3f9-4bb1-8a66-2dd6765361eb)

3. Adding signature doesn't work


https://github.com/reblaze/ui/assets/10487148/331ac7d1-f70e-400a-9451-ee888ca086b0

2023-05-10 09:11 UTC, Aviv-Galmidi requested changes
1. Getting errors for focus, missing ref?

![Screen Shot 2023-05-10 at 12 03 46](https://github.com/reblaze/ui/assets/10487148/16581f3b-078c-40b2-9fd3-a6e5f1007216)
![Screen Shot 2023-05-10 at 12 05 11](https://github.com/reblaze/ui/assets/10487148/fb0d258d-88d1-4c31-8f90-c8a2c08ebe4a)

2. Console is full of prop warnings when opening the page, please take a look at them

![Screen Shot 2023-05-10 at 12 06 01](https://github.com/reblaze/ui/assets/10487148/7225b888-d3f9-4bb1-8a66-2dd6765361eb)

3. Adding signature doesn't work


https://github.com/reblaze/ui/assets/10487148/331ac7d1-f70e-400a-9451-ee888ca086b0

2023-05-18 11:14 UTC, Aviv-Galmidi commented
Awaiting PR fixes

2023-05-22 09:12 UTC, SrdjanReblaze commented
@Aviv-Galmidi 

all issues fixed

2023-05-22 13:49 UTC, merged