V5 ga 101 backend services editor
reblaze/ui pull request #278
Opened 2023-05-10 08:08 UTC by SrdjanReblaze

![image](https://github.com/reblaze/ui/assets/125982820/93952288-5a08-4da4-a2b9-e49358500bd7)

2023-05-18 11:30 UTC, Aviv-Galmidi requested changes

2023-05-18 11:30 UTC, Aviv-Galmidi commented on src/views/saas-settings/BackendServicesEditor.vue
> +                              @update:value="resetStickyCookieName"
This function is called on initial data load which causes the next input to always be empty on data load (sticky_cookie_name)

![Screen Shot 2023-05-18 at 14 30 08](https://github.com/reblaze/ui/assets/10487148/6e7485bc-3e71-4c0f-99b5-4936c186d8ab)

2023-05-18 13:50 UTC, SrdjanReblaze commented on src/views/saas-settings/BackendServicesEditor.vue
> +                              @update:value="resetStickyCookieName"
i removed that line

2023-05-22 13:53 UTC, Aviv-Galmidi approved these changes

2023-05-22 13:53 UTC, merged