New navigation bar
reblaze/ui pull request #281
Opened 2023-05-22 08:21 UTC by AvihayMReblaze

2023-05-22 11:25 UTC, Aviv-Galmidi requested changes
1. Branch selection shouldn't take the entire height of the topbar

<img width="495" alt="Screen Shot 2023-05-22 at 13 58 19" src="https://github.com/reblaze/ui/assets/10487148/9b240bba-28f6-4de9-9d94-7e9170475355">

<img width="199" alt="Screen Shot 2023-05-22 at 13 58 47" src="https://github.com/reblaze/ui/assets/10487148/56f7c6ac-ef4a-4093-adf5-7204cd30c442">

2. Branch selection should use rbzDropdown component

3. Missing spacing between Account icon and vertical divider - should be 16px from either side

<img width="248" alt="Screen Shot 2023-05-22 at 14 00 03" src="https://github.com/reblaze/ui/assets/10487148/3403cd8f-cc9c-49af-8f0d-e7fc7b849601">

4. Menu should close after selceting an option within it

5. Menu item border is somewhat hidden by the next item

<img width="157" alt="Screen Shot 2023-05-22 at 14 12 10" src="https://github.com/reblaze/ui/assets/10487148/0b2d5e51-ac2e-441f-9e66-03e959780b23">

6. Remove option of clicking on Reblaze icon - no longer needed and looks bad

<img width="216" alt="Screen Shot 2023-05-22 at 14 14 04" src="https://github.com/reblaze/ui/assets/10487148/0f8bc893-7793-4f76-96a4-bcf03aca751b">

7. Reblaze Logo should be more to the right
<img width="252" alt="Screen Shot 2023-05-22 at 14 15 03"
 src="https://github.com/reblaze/ui/assets/10487148/e885fce8-0705-481c-b42d-d98cfceaf0bb">
<img width="248" alt="Screen Shot 2023-05-22 at 14 15 15" src="https://github.com/reblaze/ui/assets/10487148/6977dba2-0a58-4d9f-8ee1-f5a3e378c166">

8. Tests are not passing

2023-05-22 11:25 UTC, Aviv-Galmidi commented on src/components/RbzHeaderMain.vue
> +    <div class="additional-details">
Name is misleading, let's call it `actions-bar`

2023-05-22 11:25 UTC, Aviv-Galmidi commented on src/components/RbzHeaderMain.vue
> +         <svg width="80" height="17" viewBox="0 0 80 17" fill="none" xmlns="http://www.w3.org/2000/svg">
Please move the SVG to its own file instead of plain text in the code

2023-05-22 11:25 UTC, Aviv-Galmidi commented on src/components/RbzHeaderMain.vue
> +    branchesCounter: {
Not used anywhere

2023-05-22 11:25 UTC, Aviv-Galmidi commented on src/components/RbzHeaderMain.vue
> +      filterMenuVisible: false,
Name misleading, it's not a filter menu. `actionMenu` rather than `filterMenu` fits better in my opinion

2023-05-22 11:25 UTC, Aviv-Galmidi commented on src/components/RbzHeaderMain.vue
> +    setLoadingDocStatus(isLoading: boolean) {
Not needed, loadingDocCounter is not used anywhere

2023-05-22 11:25 UTC, Aviv-Galmidi commented on src/components/RbzHeaderMain.vue
> +      window.location.replace(`https://gb.docs.reblaze.com/v/v${this.docsVersion}`)
Please use window.location.href instead of .replace here - replace doesn't add the new route to the browser history which is not a desired outcome in this instance

2023-05-22 11:25 UTC, Aviv-Galmidi commented on src/components/RbzHeaderMain.vue
> +      console.log(this.userStore.logout())
Remove console.log

2023-05-22 11:25 UTC, Aviv-Galmidi commented on src/components/RbzHeaderMain.vue
> +  },
Why do we need both?

2023-05-22 11:25 UTC, Aviv-Galmidi commented on src/components/RbzHeaderMain.vue
> +  border-bottom: 1px solid #000;
$color-black not #000

But it shouldn't be black either way, it's $color-silver (#ccc)

2023-05-27 18:21 UTC, AvihayMReblaze commented on src/components/RbzHeaderMain.vue
> +  border-bottom: 1px solid #000;
Done

2023-05-27 18:22 UTC, AvihayMReblaze commented on src/components/RbzHeaderMain.vue
> +  },
I've delete the updated()

2023-05-27 18:22 UTC, AvihayMReblaze commented on src/components/RbzHeaderMain.vue
> +      console.log(this.userStore.logout())
Done

2023-05-27 18:24 UTC, AvihayMReblaze commented on src/components/RbzHeaderMain.vue
> +      window.location.replace(`https://gb.docs.reblaze.com/v/v${this.docsVersion}`)
Done

2023-05-27 18:25 UTC, AvihayMReblaze commented on src/components/RbzHeaderMain.vue
> +    setLoadingDocStatus(isLoading: boolean) {
Done

2023-05-27 18:26 UTC, AvihayMReblaze commented on src/components/RbzHeaderMain.vue
> +      filterMenuVisible: false,
Done

2023-05-27 18:27 UTC, AvihayMReblaze commented on src/components/RbzHeaderMain.vue
> +    branchesCounter: {
Removed, done.

2023-05-27 18:40 UTC, AvihayMReblaze commented on src/components/RbzHeaderMain.vue
> +    <div class="additional-details">
Done

2023-06-04 07:00 UTC, merged