New migration vue3
reblaze/ui pull request #43
Opened 2022-08-21 11:21 UTC by frontEndExpert

upgrade to vue 3:
new package.json, without errors
include spec files, without errors but without testing yet,
system is up with all components- curieFence only.

2022-08-28 07:45 UTC, Aviv-Galmidi requested changes

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/EntriesRelationList.vue
> +export type Rule = {
We can use `GlobalFilter["rule"]` type from our typing index.d.ts

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/EntriesRelationList.vue
> -      // const val = value.trim().replaceAll(/\(\?[a-z]{1,3}\)/g, '') // remove unsupported in js mode modifiers
This was commented out on purpose, as per the `TODO` comment above
The code validates an input according to a Javascript regex but the actual regex is a Rust regex, we removed this check until the validation is fixed

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/LimitOption.vue
> +      // console.log('limitOption changed')
Remove unused code

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/LimitOption.vue
> +    if (JSON.stringify(this.prevSelectedOption) != JSON.stringify(this.selectedOption)) {
We can use `_.isEqual` - https://lodash.com/docs/4.17.15#isEqual

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/TagAutocompleteInput.vue
> +      validator: (val: String) => {
Let's add a type for `single` and `multiple` - should be in `AutocompleteInput` and imported to here

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/TagAutocompleteInput.vue
> +      // this.currentEventName = eventName
Remove unused code

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/__tests__/AutocompleteInput.spec.ts
> +  let wrapper = mount(AutocompleteInput)
We do the actual mount on line 37 during `beforeEach`

maybe this? 

```suggestion
  let wrapper: VueWrapper<AutocompleteInput>
```

or this

```suggestion
  let wrapper: VueWrapper
```


Repeat for all other spec files as well

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/__tests__/AutocompleteInput.spec.ts
> +    }) as VueWrapper<any>
Maybe

```suggestion
    }) as VueWrapper<AutocompleteInput>
```

orMaybe

```suggestion
    }) as VueWrapper
```

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/__tests__/AutocompleteInput.spec.ts
> +    let input: typeof wrapper | any
DOMWrapper?

Repeat for all other spec files as well

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/__tests__/AutocompleteInput.spec.ts
> +    let dropdownItems: typeof wrapper | any
DOMWrapper[]?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/__tests__/AutocompleteInput.spec.ts
> +    let input: any
DOMWrapper?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/__tests__/LimitOption.spec.ts
> +        // options.at(1).setSelected()
Remove unused code

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/__tests__/LimitOption.spec.ts
> +        //options.at(1).setSelected()
Remove unusec code

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/components/__tests__/SideMenu.spec.ts
> +    const menuItem = wrapper.findAll('.menu-item').filter((item : any) => item.text().includes(menuItemName))
any - DOMWrapper?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/ACLEditor.vue
> +      return _.cloneDeep(this.selectedDoc as ACLProfile)
Should the type be in the props?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/ContentFilterProfileEditor.vue
> +          value: 'base64' as keyof ContentFilterProfile['decoding'],
We can add a type to the all `decodingOptions` instead of each value indivudally

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/ContentFilterProfileEditor.vue
> +      return _.cloneDeep(this.selectedDoc) as ContentFilterProfile
Should this type be in the `props`?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/ContentFilterRuleGroupEditor.vue
> +      return _.cloneDeep(this.selectedDoc as ContentFilterRuleGroup)
Should this type be in the `props`?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/ContentFilterRulesEditor.vue
> -                           @change="emitDocUpdate()"/>
Why are we not emitting this value on change anymore?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/ContentFilterRulesEditor.vue
> +      return _.cloneDeep(this.selectedDoc as ContentFilterRule)
Should this type be in the `props`?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/FlowControlPolicyEditor.vue
> +    getListEntryTitle(seqEntry: ArgsCookiesHeadersType): string {
We can change the return type to `ArgsCookiesHeadersType` and remove all the "as X" in the template

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/GlobalFilterListEditor.vue
> +      return _.cloneDeep(this.selectedDoc as GlobalFilter)
Should this typing be in the `props`?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/GlobalFilterListEditor.vue
> +    // updateRule(newRule: GlobalFilter['rule']) {
Remove unused code

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/GlobalFilterListEditor.vue
> +      console.log('GlobalFilterListEditor url: ', url)
Remove console log

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/RateLimitsEditor.vue
> +      removable: false,
Is this used anywhere? remove if not

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/RateLimitsEditor.vue
> +      return _.cloneDeep(this.selectedDoc as RateLimit)
Maybe this type should be in the `props`?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/RateLimitsEditor.vue
> -        this.$forceUpdate()
If I remember correctly, this was done to force a vue view update, make sure the connected security policies entries are displayed correctly (table caleled `Linked Security Policies` I think)

If it's not needed, remove the commented code

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/doc-editors/SecurityPoliciesEditor.vue
> +      return _.cloneDeep(this.selectedDoc as SecurityPolicy)
Should this type be in the `props`?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/router/index.ts
> +// Vue.use(VueRouter)
Remove unused code

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/router/index.ts
>  // #DEPRECATED: remove /db redirect on version 1.6.0, because this just a legacy for API v1 in 1.5.0.
Let's fix this as we moved to 1.6.0
remove: `{path: 'db', name: 'MasterComponent', redirect: '/CurieDB'},`

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/router/index.ts
> +      {path: 'CurieDB', name: 'CurieDBEditor', component: () => import('../views/CurieDBEditor.vue')},
Let's stick with @ for the import instead of the relative path
```suggestion
      {path: 'CurieDB', name: 'CurieDBEditor', component: () => import('@/views/CurieDBEditor.vue')},
```

Same for the next few lines as well

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/router/index.ts
> +  // base: process.env.BASE_URL,
Remove unused code

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +      set(newDoc: any): void {
any - `DocumentType` ?

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/views/DocumentSearch.vue
> +// import Vue, {VueConstructor} from 'vue'
Remove unused code

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/views/DocumentSearch.vue
> +        component: any, // VueConstructor
Remove unused code, fix `any` type

2022-08-28 07:45 UTC, Aviv-Galmidi commented on src/vue-shims.d.ts
> +      // ... more stuff
Let's remove this comment

2022-09-06 13:17 UTC, Aviv-Galmidi requested changes
Please remove `.DS_Store` file, `src/assets/logo.7f7c423d.png` image, and `.vscode` directory and all other unnecessary files

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/components/AutocompleteInput.vue
> +  mounted() {
Please return `mounted` to the location it was originally in, to keep the history cleaner

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/components/EntriesRelationList.vue
> +  // watch(rule, this.modifyRule),
Remove unused code

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/components/EntriesRelationList.vue
> +    modifyRule() {
Remove unused function

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/components/HeaderMain.vue
> -import {version} from '@/../package.json'
Why can't we leave it as is? Does this not work anymore?

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/components/LimitOption.vue
> +  updated() {
Please return the `updated()` to its original location, to keep the history as clean as possible

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/components/ts-shim.d.ts
> +declare module '*.vue' {
Do we need this file?

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/doc-editors/ContentFilterProfileEditor.vue
> +          checked: false,
Why is this neccessary? With this we're going to need to manage multiple values for checked/unchecked
For instance, on refersh the checked values are always false now, regardless of actual value on object

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/doc-editors/ContentFilterRulesEditor.vue
> -                           @change="emitDocUpdate()"/>
Fixed in my [PR to this branch](https://github.com/reblaze/ui/pull/54)

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/main.ts
> +declare module '@vue/runtime-core' {
We have the same declration in vue-shims.d.t.s - do we need both?

2022-09-06 13:17 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +      componentsMap: {
Please return this variable to its original location, to keep the history as clean as possible

2022-09-06 13:17 UTC, Aviv-Galmidi commented on tsconfig.json
>  {
Remove all unused configuration settings, make sure we need all the newly added settings

2022-09-06 13:17 UTC, Aviv-Galmidi commented on typings/sfc.d.ts
> +declare module '*.vue' {
Do we need this file?

2022-09-06 13:17 UTC, Aviv-Galmidi commented on vue.config.js
> -    // proxy: 'http://localhost:5000'
Please return this comment, it shows where the proxy is pointing to (Swagger)

2022-09-06 13:17 UTC, Aviv-Galmidi commented on jest.setup.ts
> +declare module '@vue/runtime-core' {
We have the same settings in vue-shims.d.ts - do we need both?

2022-09-06 14:15 UTC, frontEndExpert commented on jest.setup.ts
> +// @ts-ignore
It does not work without it

2022-09-06 14:16 UTC, frontEndExpert commented on jest.setup.ts
> +declare module '@vue/runtime-core' {
fixed

2022-09-06 14:33 UTC, frontEndExpert commented on jest.setup.ts
> +      $goto: any,
removed

2022-09-06 14:39 UTC, frontEndExpert commented on src/assets/__tests__/Utils.spec.ts
> +function currentEventLoopEnd() {
replaced with nextTick()

2022-09-06 14:47 UTC, frontEndExpert commented on src/components/EntriesRelationList.vue
> +                              @change="validateValue( sectionIndex, newEntryItem.firstAttr)"
input done please check

2022-09-06 14:58 UTC, frontEndExpert commented on src/components/EntriesRelationList.vue
> +    modifyRule() {
Yes it is not used... so removed

2022-09-06 15:02 UTC, frontEndExpert commented on src/components/HeaderMain.vue
> -import {version} from '@/../package.json'
Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)

2022-09-06 15:04 UTC, frontEndExpert commented on src/components/LimitOption.vue
> +  updated() {
ok

2022-09-06 15:21 UTC, frontEndExpert commented on src/doc-editors/ACLEditor.vue
> +      return _.cloneDeep(this.selectedDoc as ACLProfile)
It did not work for me.
Maybe you can think of a better way.

2022-09-06 15:37 UTC, frontEndExpert commented on src/doc-editors/ContentFilterProfileEditor.vue
> +          value: 'base64' as keyof ContentFilterProfile['decoding'],
done, please check

2022-09-06 18:05 UTC, frontEndExpert commented on src/doc-editors/ContentFilterProfileEditor.vue
> +      return _.cloneDeep(this.selectedDoc) as ContentFilterProfile
It does not let me put it in props: {
    selectedDoc: Object,

2022-09-06 18:23 UTC, frontEndExpert commented on src/doc-editors/ContentFilterProfileEditor.vue
> +          checked: false,
I changed it back but please confirm that it is working as wanted even though the testing pass.

2022-09-06 18:33 UTC, frontEndExpert commented on src/doc-editors/ContentFilterRulesEditor.vue
> -                           @change="emitDocUpdate()"/>
Emited without errors

2022-09-06 18:33 UTC, frontEndExpert commented on src/doc-editors/ContentFilterRulesEditor.vue
> +      return _.cloneDeep(this.selectedDoc as ContentFilterRule)
maybe it should but it does not let me.

2022-09-06 18:41 UTC, frontEndExpert commented on src/doc-editors/FlowControlPolicyEditor.vue
> +    getListEntryTitle(seqEntry: ArgsCookiesHeadersType): string {
not clear.

2022-09-06 18:44 UTC, frontEndExpert commented on src/doc-editors/RateLimitsEditor.vue
> +      removable: false,
yes its in the code and template

2022-09-06 18:45 UTC, frontEndExpert commented on src/doc-editors/RateLimitsEditor.vue
> +      return _.cloneDeep(this.selectedDoc as RateLimit)
same issue

2022-09-07 02:22 UTC, frontEndExpert commented on src/doc-editors/RateLimitsEditor.vue
> -        this.$forceUpdate()
it seems resolved already. limit options look same as in docker.
not sure what Linked Security Policies look like.

2022-09-07 02:24 UTC, frontEndExpert commented on src/doc-editors/GlobalFilterListEditor.vue
> +      return _.cloneDeep(this.selectedDoc as GlobalFilter)
It was not fit in the props.

2022-09-07 02:31 UTC, frontEndExpert commented on src/main.ts
> +declare module '@vue/runtime-core' {
there 1 in main 
and 1 in jest.setup
vue-shim doesn't have it anymore.

2022-09-07 02:47 UTC, frontEndExpert commented on typings/sfc.d.ts
> +declare module '*.vue' {
Deleted successfully

2022-09-07 03:39 UTC, frontEndExpert commented on typings/sfc.d.ts
> +declare module '*.vue' {
but then returned because it helps to find the modules.
without it it was errored with husky when committing my changes.

2022-09-07 06:55 UTC, Aviv-Galmidi requested changes

2022-09-07 06:55 UTC, Aviv-Galmidi commented on jest.config.js
> +  collectCoverage: true,
I'm not sure if we need this, we have two scripts one that does collect coverage and one that doesn't, forcing to always collect coverage will remove our abilities to run the tests without coverage (they run faster, just to see that everything passes)

2022-09-07 06:55 UTC, Aviv-Galmidi commented on jest.config.js
> +    '<rootDir>/**/__tests__/*.spec.ts',
Do we need these 3 `testMatch` additions?
`'<rootDir>/**/*.spec.(js|jsx|ts|tsx)',` should cover all test cases described in the other 3 as well

2022-09-07 06:55 UTC, Aviv-Galmidi commented on jest.setup.ts
> +// @ts-ignore
What doesn't work without it? the first `it` is ambiguous

I removed it locally and was able to run `npm run lint:ts`, `npm run lint:js` and `npm run coverage` all without errors or warnings

2022-09-07 06:55 UTC, Aviv-Galmidi commented on src/assets/__tests__/Utils.spec.ts
> +      // await currentEventLoopEnd()
Can we remove these three comments it not used?

2022-09-07 06:55 UTC, Aviv-Galmidi commented on src/components/LimitOption.vue
> +    if (!_.isEqual(this.prevSelectedOption, this.selectedOption)) {
Why is this needed? What is it trying to fix?
If it is needed, we'll also need to add a setter for `prevSelectedOption` inside this `if` check, as `mounted` is only called once for this component

2022-09-07 06:55 UTC, Aviv-Galmidi commented on src/doc-editors/FlowControlPolicyEditor.vue
> -                           data-qa="remove-sequence-btn"
Please return the double qoutes instead of single qoute for attribute values

2022-09-07 06:55 UTC, Aviv-Galmidi commented on src/doc-editors/FlowControlPolicyEditor.vue
> +    getListEntryTitle(seqEntry: ArgsCookiesHeadersType): ArgsCookiesHeadersType {
Is this method needed? Only used in 1 location and takes more code than actually calling `.title as type`

2022-09-07 06:55 UTC, Aviv-Galmidi commented on src/doc-editors/RateLimitsEditor.vue
> +      removable: false,
The template is using `removable` inside `v-for` with a bad setter `:set=removable = localDoc.thresholds.length > 1`

We can change this into a computed value

2022-09-07 06:55 UTC, Aviv-Galmidi commented on tsconfig.json
> +      "@/views/*": [ "./src/views/*" ],
This seems redundant `"@/views/*"` will be converted to `"./src/views/*"` by the first path value, same goes for the `doc-editors` value

2022-09-07 17:15 UTC, frontEndExpert commented on src/components/__tests__/SideMenu.spec.ts
> +    const menuItem = wrapper.findAll('.menu-item').filter((item : any) => item.text().includes(menuItemName))
{
102      const match: DOMWrapper<any> = sectionItems.find((sectionItem: DOMWrapper<any>) => {
<any> ?

2022-09-07 18:34 UTC, frontEndExpert commented on src/doc-editors/FlowControlPolicyEditor.vue
> +    getListEntryTitle(seqEntry: ArgsCookiesHeadersType): string {
sequenceItemEntries(sequenceIndex: number): (string | any[])[]

2022-09-07 19:11 UTC, frontEndExpert commented on mocks/fileMock.js
> +export default '';
deleted. we now use filetransformer.js instead

2022-09-07 19:15 UTC, frontEndExpert commented on src/doc-editors/ContentFilterProfileEditor.vue
> +          checked: false,
maybe we need a unit test for this?

2022-09-07 19:48 UTC, frontEndExpert commented on jest.config.js
> +  collectCoverage: true,
pass without

2022-09-07 19:48 UTC, frontEndExpert commented on jest.config.js
> +    '<rootDir>/**/__tests__/*.spec.ts',
only 1 left

2022-09-07 19:51 UTC, frontEndExpert commented on src/assets/__tests__/Utils.spec.ts
> +      // await currentEventLoopEnd()
removed

2022-09-07 19:59 UTC, frontEndExpert commented on src/components/LimitOption.vue
> +    if (!_.isEqual(this.prevSelectedOption, this.selectedOption)) {
5 test fails without it

2022-09-07 20:10 UTC, frontEndExpert commented on src/doc-editors/FlowControlPolicyEditor.vue
> +    getListEntryTitle(seqEntry: ArgsCookiesHeadersType): ArgsCookiesHeadersType {
replaced

2022-09-07 20:37 UTC, frontEndExpert commented on src/doc-editors/FlowControlPolicyEditor.vue
> +    getListEntryTitle(seqEntry: ArgsCookiesHeadersType): ArgsCookiesHeadersType {
after the change to .title 3 tests failed

2022-09-08 05:07 UTC, Aviv-Galmidi reviewed
Please remove `.DS_Store` and `src/ts-shim.d.ts` from the PR

2022-09-08 05:09 UTC, Aviv-Galmidi commented on tsconfig.json
> +    ],
Is your compiler okay with that? I think JSON files do not allow trailing comma

2022-09-08 05:20 UTC, frontEndExpert commented on src/doc-editors/FlowControlPolicyEditor.vue
> +                        {{ getListEntryTitle(sequenceEntry[0] as ArgsCookiesHeadersType) }}
removed. what is the guideline, best practice?
we try to avoid casting in template, right?

2022-09-08 05:26 UTC, frontEndExpert commented on tsconfig.json
> +    ],
good catch. Removed!, my compiler did not complained about it.

2022-09-08 10:00 UTC, Aviv-Galmidi approved these changes

2022-09-08 10:21 UTC, merged