Cloud functions
reblaze/ui pull request #61
Opened 2022-09-21 18:07 UTC by ux-AylonS

New CloudFunction component SecurityPolicyConnections and more

2022-09-22 07:15 UTC, Aviv-Galmidi approved these changes

2022-09-22 07:15 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +        console.log('load config', configs)
We don't need this log, we have a similar one in line 433

2022-09-22 07:15 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +      if (document==='cloudfunctions') {
Add a TODO to remove this mock

2022-09-22 07:15 UTC, Aviv-Galmidi commented on src/views/DocumentList.vue
> +import {ColumnOptions, Commit, Document, DocumentType, GenericObject, CloudFunctionsPhase} from '@/types'
Keep types in alphabetical order

```suggestion
import {CloudFunctionsPhase, ColumnOptions, Commit, Document, DocumentType, GenericObject} from '@/types'
```

2022-09-22 07:15 UTC, Aviv-Galmidi commented on src/views/DocumentList.vue
> +      docsDisplayData: [] as GenericObject[],
What's this new variable?

2022-09-22 07:15 UTC, Aviv-Galmidi commented on src/views/DocumentList.vue
> +      cloudPhases: DatasetsUtils.cloudPhases as CloudFunctionsPhase,
Is this being used anywhere? I can't find it

2022-09-22 07:15 UTC, Aviv-Galmidi commented on src/views/documentListConst.ts
> +      classes: 'width-250px',
Removed width from description so it would take as much room as possible
Added `ellipsis` for long descriptions

```suggestion
      classes: 'ellipsis',
```

2022-09-22 07:15 UTC, Aviv-Galmidi commented on src/views/documentListConst.ts
> +      classes: 'width-300px',
300px seems excessive, isn't it way too wide like that? Let's try to find a width that is just enough to cintain the titles for these

2022-09-22 07:15 UTC, Aviv-Galmidi commented on src/assets/DatasetsUtils.ts
> +const cloudPhases: CloudFunctionsPhase = {
Can we possibly use the titles instead of this const, and just have the list of possiblities in the component itself

e.g.
In the component have a list of cloud phases `['requestpre', 'requestpost', 'responsepre', 'responsepost']` which we'll run on for the select options, and then pull the full text from `titles`

That way, we'll reduce some of the duplicated code

2022-09-22 08:36 UTC, Aviv-Galmidi requested changes

2022-09-22 08:36 UTC, Aviv-Galmidi commented on src/doc-editors/CloudFunctionsEditor.vue
> +    apiPath: String,
add the apiPath to the editor - look at ACLEditor (or any other doc editor) to understand how it's being used

2022-09-22 12:21 UTC, ux-AylonS commented on src/assets/DatasetsUtils.ts
> +const cloudPhases: CloudFunctionsPhase = {
changed

2022-09-22 12:23 UTC, ux-AylonS commented on src/components/SecurityPoliciesConnections.vue
> +  emits: ['update:selectedDocId', 'go-to-route'],
deleted

2022-09-22 12:25 UTC, ux-AylonS commented on src/doc-editors/CloudFunctionsEditor.vue
> +                         data-qa="cloudfunctions-name-input"
done

2022-09-22 12:37 UTC, ux-AylonS commented on src/doc-editors/CloudFunctionsEditor.vue
> +    apiPath: String,
It presents in the Version History.
now we have double.

2022-09-22 12:42 UTC, ux-AylonS commented on src/doc-editors/CloudFunctionsEditor.vue
> +<style scoped lang='scss'>
no style only global

2022-09-22 12:56 UTC, ux-AylonS commented on src/views/DocumentList.vue
> +      docsDisplayData: [] as GenericObject[],
deleted

2022-09-22 12:59 UTC, ux-AylonS commented on src/views/DocumentList.vue
> +      cloudPhases: DatasetsUtils.cloudPhases as CloudFunctionsPhase,
deleted

2022-09-29 06:59 UTC, Aviv-Galmidi commented on src/components/SecurityPoliciesConnections.vue
> +                <th class="is-size-7 ellipsis">Domain Match</th>
We should give either the Domain Match column or the Entry Match column a set width. As of right now, if we have a long domain but no entry the system would look different than no domain and long entry

2022-09-29 06:59 UTC, Aviv-Galmidi commented on src/components/SideMenu.vue
> +      console.log('response', response.data)
remove console.log

2022-09-29 06:59 UTC, Aviv-Galmidi commented on src/components/__tests__/SecurityPoliciesConnections.spec.ts
> +// import {nextTick} from 'vue'CloudFunctions
Remove unused import

2022-09-29 06:59 UTC, Aviv-Galmidi commented on src/doc-editors/CloudFunctionsEditor.vue
> +    selectedDoc: Object,
add `PropType`

2022-09-29 06:59 UTC, Aviv-Galmidi commented on src/doc-editors/CloudFunctionsEditor.vue
> +// import SecurityPoliciesConnections from '@/components/SecurityPoliciesConnections.vue'
Remove unused code

2022-09-29 06:59 UTC, Aviv-Galmidi commented on src/doc-editors/CloudFunctionsEditor.vue
> +  // components: {
Remove unused code

2022-09-29 06:59 UTC, Aviv-Galmidi commented on src/doc-editors/CloudFunctionsEditor.vue
> +    // emitGoToRoute(url: string) {
Remove unused code

2022-09-29 06:59 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +      // TODO remove this mock
Remove the mock

2022-09-29 07:16 UTC, ux-AylonS commented on src/components/SecurityPoliciesConnections.vue
> +                <th class="is-size-7 ellipsis">Domain Match</th>
<th class="is-size-7 ellipsis">Domain Match</th>
<th class="is-size-7 width-300px">Entry Match</th>

2022-09-29 10:13 UTC, Aviv-Galmidi submitted a review, later dismissed
Looks good, just need to connect this code to the saas backend server and then we can merge this PR

2022-09-29 10:13 UTC, Aviv-Galmidi commented on src/components/SecurityPoliciesConnections.vue
> +                <th class="is-size-7 ellipsis">Domain Match</th>
We can leave the ellipsis as it was, just needed to add a width to one of them (you've added to entry match which is fine)

2022-10-02 12:51 UTC, Aviv-Galmidi commented on src/assets/DatasetsUtils.ts
> +  'cloudfunctions-singular': 'Cloud Functions',
```suggestion
  'cloudfunctions': 'Cloud Functions',
  'cloudfunctions-singular': 'Cloud Function',
```

2022-10-02 12:51 UTC, Aviv-Galmidi commented on src/assets/DatasetsUtils.ts
> +  'cloudfunctions-singular': 'Cloud Functions',
one title for singular, one title for multiple (non singular)

2022-10-02 12:51 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +        return `/config/d/cloudfunctions/e/${this.selectedDocID}`
should this be `cloud-functions` instead of `cloudfunctions`?
If `cloud-functions` is the actual API type, we can use it instead of `cloudfunctions` for `this. selectedDocType` and all internal uses

2022-10-02 12:51 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +      console.log('this.selectedDocType', this.selectedDocType)
Please remove this log

2022-10-02 12:51 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +        console.log('Error saving', error)
We already send the error to the console in requestUtils

2022-10-02 12:51 UTC, Aviv-Galmidi commented on src/views/DocumentList.vue
> +        <git-history v-if="selectedDocType !=='cloudfunctions'" :gitLog="gitLog"
new line for each attribute

2022-10-02 12:51 UTC, Aviv-Galmidi commented on src/views/DocumentList.vue
> +      return `${this.apiRoot}/${this.apiVersion}/${this.apiVersion}/`+
We can leave this as it was

2022-10-02 12:51 UTC, Aviv-Galmidi commented on src/views/documentListConst.ts
> +      displayFunction: (phase: CloudFunctionsPhaseType) => {
You get an full Cloud Function here (entire row), not a phase (cell)

2022-10-02 13:10 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +        return `/config/d/cloudfunctions/e/${this.selectedDocID}`
yes

2022-10-02 13:16 UTC, ux-AylonS commented on src/views/documentListConst.ts
> +      displayFunction: (phase: CloudFunctionsPhaseType) => {
displayFunction: (item: CloudFunction) => {
        const titles = DatasetsUtils.titles
        return titles[item.phase]
      },

2022-10-02 13:22 UTC, Aviv-Galmidi commented on src/assets/DatasetsUtils.ts
> +  'cloudfunctions-singular': 'Cloud Functions',
```suggestion
  'cloudfunctions-singular': 'Cloud Function',
```

`'cloudfunctions-singular': 'Cloud Functions',` - That's still not singular

2022-10-02 13:23 UTC, Aviv-Galmidi commented
3 tests are failing

2022-10-02 13:29 UTC, ux-AylonS commented on src/assets/DatasetsUtils.ts
> +  'cloudfunctions-singular': 'Cloud Functions',
Thanks

2022-10-02 18:50 UTC, Aviv-Galmidi commented on src/views/DocumentEditor.vue
> +      const docName = this.selectedDoc ? this.selectedDoc.name : 'no name'
SwitchDocID isn't possible if docs is empty, which means we always should have a selectedDoc, when did you reach a stage when we didn't?

2022-10-02 18:50 UTC, Aviv-Galmidi commented on src/views/__tests__/DocumentEditor.spec.ts
> +      if (path === `/reblaze/api/v3/configs/${branch}/d/cloud-functions/`) {
That's not the right path for cloud functions

2022-10-02 18:50 UTC, Aviv-Galmidi commented on src/views/__tests__/DocumentEditor.spec.ts
> +      const wantedFileData = wrapper.vm.docs // aclDocs
Why is this change needed, assuming `wrapper.vm.docs` actually holds aclDocs like the comment suggests

2022-10-02 18:50 UTC, Aviv-Galmidi commented on src/views/__tests__/DocumentEditor.spec.ts
> +      await docTypeSelection.setValue(docTypeOptions.at(4).element.value)
Why is this change needed? Seems kind of random

2022-10-02 20:24 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +      const docName = this.selectedDoc ? this.selectedDoc.name : 'no name'
during testing

2022-10-02 20:50 UTC, ux-AylonS commented on src/views/__tests__/DocumentEditor.spec.ts
> +      await docTypeSelection.setValue(docTypeOptions.at(4).element.value)
it is not random it simply choose another case to test this feature.
at(4) is aclprofile

2022-10-02 20:52 UTC, ux-AylonS commented on src/views/__tests__/DocumentEditor.spec.ts
> +      const wantedFileData = wrapper.vm.docs // aclDocs
actually it did not pick up the aclDocs mockup but rather the default docs
therefore I point the this to docs.

2022-10-02 20:55 UTC, ux-AylonS commented on src/views/__tests__/DocumentEditor.spec.ts
> +      if (path === `/reblaze/api/v3/configs/${branch}/d/cloud-functions/`) {
fixed

2022-10-02 20:59 UTC, ux-AylonS commented on src/views/DocumentEditor.vue
> +      const docName = this.selectedDoc ? this.selectedDoc.name : 'no name'
it fixed now

2022-10-02 21:22 UTC, ux-AylonS commented on src/views/__tests__/DocumentEditor.spec.ts
> +      const wantedFileData = wrapper.vm.docs // aclDocs
Download is triggered
but the data is different

2022-10-03 05:04 UTC, Aviv-Galmidi commented on src/views/__tests__/DocumentEditor.spec.ts
> +      await docTypeSelection.setValue(docTypeOptions.at(4).element.value)
But why do we need to change which doc type we were using? What's wrong with the first doc type?

2022-10-03 06:23 UTC, Aviv-Galmidi commented on src/views/__tests__/DocumentEditor.spec.ts
> +      await docTypeSelection.setValue(docTypeOptions.at(4).element.value)
The default route for the tests is `aclprofiles` so the test now doesn't do anything, what is the issue with keeping it at 0 to select `globalfilters`?

2022-10-03 06:23 UTC, Aviv-Galmidi commented on src/views/__tests__/DocumentEditor.spec.ts
> +      // const wantedFileName = 'aclprofiles'
I don't understand this change

2022-10-03 13:38 UTC, Aviv-Galmidi approved these changes

2022-10-03 13:51 UTC, merged