Rate limit modifications
reblaze/ui pull request #71
Opened 2022-10-03 07:06 UTC by ux-AylonS

New Rate Limit modifications

2022-10-03 09:03 UTC, Aviv-Galmidi requested changes

2022-10-03 09:03 UTC, Aviv-Galmidi commented on src/doc-editors/__tests__/RateLimitsEditor.spec.ts
> +      const wantedType = Object.keys(rateLimitsDocs[0].key[0])[0]
That test is for `pairtwith` not `key` (Event in the UI)

2022-10-03 09:03 UTC, Aviv-Galmidi commented on src/doc-editors/__tests__/RateLimitsEditor.spec.ts
> +      expect(wrapper.vm.localDoc.key.length).toEqual(2)
Read the test name again. We want to test that we DO NOT remove a key when only one key exists. If we start with 3 keys by default you can remove 2 of them before testing the last one can't be removed, or set the initial data for this test to be a rate limit with only one key

2022-10-03 11:19 UTC, ux-AylonS commented on src/doc-editors/SecurityPoliciesEditor.vue
> +                <td class="is-size-7 width-200px ellipsis entry-match"
done. the problem is with small screens under 1300px

2022-10-04 02:43 UTC, ux-AylonS commented on src/assets/DatasetsUtils.ts
> +          'id': id,
Is this should be here?

2022-10-04 05:49 UTC, Aviv-Galmidi reviewed
Need to resolve conflicts

2022-10-04 05:49 UTC, Aviv-Galmidi commented on public/static/bulma.css
> +/*! bulma.io v0.9.0 | MIT License | github.com/jgthms/bulma */@-webkit-keyframes spinAround{from{transform:rotate(0)}to{transform:rotate(359deg)}}@keyframes spinAround{from{transform:rotate(0)}to{tra
What did you change in Bulma?

2022-10-04 05:49 UTC, Aviv-Galmidi commented on src/assets/DatasetsUtils.ts
> +          'id': id,
Yes that was part of the task, adding `id` to map entry in Security Policy

2022-10-04 05:49 UTC, Aviv-Galmidi commented on src/assets/DatasetsUtils.ts
> +          'id': id,
Yes that was part of the task, adding id to map entry in Security Policy

2022-10-06 06:39 UTC, Aviv-Galmidi commented on src/components/securityPoliciesConnections.vue
> +<div>
Fix indents in this page

2022-10-06 10:29 UTC, Aviv-Galmidi approved these changes

2022-10-06 10:32 UTC, merged