Automatic tags
reblaze/ui pull request #81
Opened 2022-10-17 05:20 UTC by ux-AylonS

2022-10-19 11:05 UTC, Aviv-Galmidi requested changes

2022-10-19 11:05 UTC, Aviv-Galmidi commented on src/doc-editors/ACLEditor.vue
> +    createTagElement(tag: string): string {
Can we move this to a single location? There's a lot of reptitiveness
Either a component that holds this html as template or maybe a function in Utils.ts. I think a component would work best here that way we can have the styling and template in a single location

We can also add the tags wrapper to this new component
`
<div class="is-size-7 document-automatic-tags">
  Automatic Tags:
  <div v-html="automaticTags"></div>
</div>
`

or maybe a v-for for a list of automatic tags we get from props

2022-10-19 11:05 UTC, Aviv-Galmidi commented on src/doc-editors/ContentFilterProfileEditor.vue
> +    updateContentType(value: string, event: any): void {
Let's try to avoid the `any` type - What's wrong with the previous `InputEvent`?

2022-10-19 11:05 UTC, Aviv-Galmidi commented on src/doc-editors/FlowControlPolicyEditor.vue
> +      // TODO
Remove `TODO`

2022-10-19 19:26 UTC, ux-AylonS commented on src/doc-editors/ACLEditor.vue
> +    createTagElement(tag: string): string {
a new component AutomaticTags.vue

2022-10-19 19:29 UTC, ux-AylonS commented on src/doc-editors/ContentFilterProfileEditor.vue
> +    updateContentType(value: string, event: any): void {
InputEvent not work
but Event works

2022-10-20 06:50 UTC, Aviv-Galmidi requested changes

2022-10-20 06:50 UTC, Aviv-Galmidi commented on src/components/AutomaticTags.vue
> +  // data() {
Remove unused code

2022-10-20 06:50 UTC, Aviv-Galmidi commented on src/components/AutomaticTags.vue
> +      if (this.selectedDocType === 'aclprofiles') {
Instead of this huge if/else we can send the tags directly through the props instead of selectedDocType and selectedDoc

2022-10-20 10:06 UTC, Aviv-Galmidi commented on src/components/AutomaticTags.vue
> +    tagID: String,
We can simply send prop "tags" which will be an array of tags

2022-10-20 12:11 UTC, ux-AylonS commented on src/components/AutomaticTags.vue
> +    tagID: String,
sending 1 object prop

2022-10-21 13:36 UTC, Aviv-Galmidi commented
Merged in #92

2022-10-21 13:36 UTC, closed without merging