modifications done
reblaze/ui pull request #87
Opened 2022-10-19 09:22 UTC by ux-AylonS

Signed-off-by: AylonS <aylons@reblaze.com>

2022-10-19 10:54 UTC, Aviv-Galmidi requested changes

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
>        // Collapsible cards
Let's move the newly added collapsible flags here
`isTrustedCollapsed` and `isAdvancedCollapsed`

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +    getAddress(address: any) {
Not being used anywhere?

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +    async parseData({trustedNets}: {trustedNets: any}): Promise<void> {
Not being used anywhere?

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +    pathname() {
Not being used anywhere?

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +    deleteTrustedElement() {
Add the actual delete functionailty

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                <!--p-- class="control">
?

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                      <button class="button is-small has-text-danger delete-branch-toggle"
```suggestion
                      <button class="button is-small has-text-danger delete-web-proxy-toggle"
```

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                      <input class="input is-small delete-branch-input"
```suggestion
                      <input class="input is-small delete-web-proxy-input"
```

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                             data-qa="confirm-branch-name-input"
```suggestion
                             data-qa="confirm-web-proxy-name-input"
```

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                             title="Doc ID to Delete"
confirm with name not ID

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                      <button class="button is-danger is-small delete-branch-cancel"
```suggestion
                      <button class="button is-danger is-small delete-web-proxy-cancel"
```

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                              data-qa="cancel-delete-branch-btn"
```suggestion
                              data-qa="cancel-delete-web-proxy-btn"
```

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                      <button class="button is-primary is-small delete-branch-confirm"
```suggestion
                      <button class="button is-primary is-small delete-web-proxy-confirm"
```

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                              data-qa="confirm-delete-branch-btn"
```suggestion
                              data-qa="confirm-delete-web-proxy-btn"
```

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                    <input class="input is-small domain-name"
Sorry this wasn't clear enough in the task, the field should be a text area which accepts multiple hosts (domains)

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                           title="Domain name"
Change title to match the new label

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                           placeholder="Domain name"
Change placeholder to match the new label

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +                            <select v-model="selectedWebProxy.ssl_certificate" >
Fix indents for this file

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +    // isSelectedWebProxyNameToDeleteValid(): boolean {
?

2022-10-19 10:54 UTC, Aviv-Galmidi commented on src/types/index.d.ts
> +  type Certificates1 = {
No need for this type in here, also `Certificates1` is not informative

2022-10-19 11:41 UTC, ux-AylonS commented on src/doc-editors/ProxyTemplateEditor.vue
> +      this.trustedData = [{
even planet return trusted_net as string
without address and comment
what to do?

2022-10-19 14:16 UTC, ux-AylonS commented on src/doc-editors/WebProxyEditor.vue
> +                             title="Doc ID to Delete"
According to swagger 
DELETE is by id
and there is no Name in the schema
IT IS ONLY EXIST in our datasetUtils.

2022-10-19 17:15 UTC, ux-AylonS commented on src/doc-editors/WebProxyEditor.vue
> +                    <input class="input is-small domain-name"
multiple hosts like tags or simple text?

2022-10-19 17:15 UTC, ux-AylonS commented on src/doc-editors/WebProxyEditor.vue
> +                             title="Doc ID to Delete"
I wait for a reply from zuri

2022-10-19 17:16 UTC, ux-AylonS commented on src/doc-editors/ProxyTemplateEditor.vue
> +    deleteTrustedElement() {
I wait for reply from zuri regarding the scheme of trusted sources

2022-10-20 02:32 UTC, ux-AylonS commented on src/doc-editors/ProxyTemplateEditor.vue
> +    deleteTrustedElement() {
now, according to Zuri,  we wait for shai to implement it under proxy template

2022-10-20 06:53 UTC, Aviv-Galmidi requested changes

2022-10-20 06:53 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +// type TrustedSources = {
Remove unused code

2022-10-20 06:53 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +      this.trustedData = response.data.trusted_net.map((trusted: string)=> {
this will throw an error if there is no `trusted_net` property, we need to add optional chaining (response?.data?...)

2022-10-20 06:53 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +    deleteTrustedElement(id: string) {
What does this function suppose to do?

2022-10-20 08:42 UTC, ux-AylonS commented on src/doc-editors/ProxyTemplateEditor.vue
> +      this.trustedData = response.data.trusted_net.map((trusted: string)=> {
we also need to come back after this will be done by backend

2022-10-20 08:43 UTC, ux-AylonS commented on src/doc-editors/ProxyTemplateEditor.vue
> +    deleteTrustedElement(id: string) {
we need to wait for backend to develop trusted_net.
so we can get it and delete it.
there is none now.

2022-10-20 09:56 UTC, ux-AylonS commented on src/doc-editors/WebProxyEditor.vue
> +                             title="Doc ID to Delete"
Just a place holder until will be implemented by backend

2022-10-22 07:36 UTC, Aviv-Galmidi requested changes

2022-10-22 07:36 UTC, Aviv-Galmidi commented on src/components/RbzTable.vue
> +
Let's avoid using float, this should work:

```suggestion
.rbz-table .menu {
    display: inline-flex;
    justify-content: flex-end;
    width: 100%;
}
```

2022-10-22 07:36 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +.cell-height {
Do we really need this? The idea was to have the inputs aligned between the two columns

2022-10-22 07:36 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +.add-new-trusted-source {
We can use `ml-1` or something close to it in order to achieve a similar result

2022-10-22 07:36 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +    // placeholder until to be implemented by backend
Should be implemented now, if not let's add `// TODO` to the start so git will pick this up and remind us about it

2022-10-22 07:36 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +.height-100px {
We already have this class in `main.scss` no need to recreate it

2022-10-22 07:36 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
>                <div class="column is-4">
If this isn't being used we can remove it

2022-10-22 07:36 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +          // this is a mockup data. need to take out as soon as we get certificate to work
Should be working now, if not let's add a `// TODO` so git will pick this up

2022-10-22 07:36 UTC, Aviv-Galmidi commented on src/assets/styles/main.scss
> +.height-150px {
Not being used anywhere

2022-10-22 08:12 UTC, ux-AylonS commented on src/doc-editors/ProxyTemplateEditor.vue
> +.cell-height {
some field sections were overlapping another
I fixed the first 2 to align together in both columns

2022-10-22 08:18 UTC, ux-AylonS commented on src/doc-editors/ProxyTemplateEditor.vue
> +.add-new-trusted-source {
changed class into ml-3px

2022-10-22 08:24 UTC, ux-AylonS commented on src/doc-editors/WebProxyEditor.vue
> +          // this is a mockup data. need to take out as soon as we get certificate to work
I add ed TODO. It might be done already, I was not able to add certificates in the swagger so I can find them here.
maybe I can just get a help to create some certificates in order to test this.

2022-10-22 08:26 UTC, ux-AylonS commented on src/assets/styles/main.scss
> +.height-150px {
I tested it with proxy-templates, since not in use after all, deleted.

2022-10-22 09:50 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +.add-new-trusted-source {
That's not a real bulma class, it's `ml-#` where # is a number between 0 and 6
https://bulma.io/documentation/helpers/spacing-helpers/#list-of-all-spacing-helpers

2022-10-22 10:03 UTC, Aviv-Galmidi commented on src/doc-editors/WebProxyEditor.vue
> +          // this is a mockup data. need to take out as soon as we get certificate to work
To create a certificate we can use something like OpenSSL
https://stackoverflow.com/a/10176685/14882879
Then we send the data to the saasbackend according to the schema

I just tested it locally on my saasbackend and this works

2022-10-22 10:08 UTC, Aviv-Galmidi commented on src/doc-editors/ProxyTemplateEditor.vue
> +.cell-height {
We can resolve this by giving the fields a set height similar to Frontend accordion
That way we won't have two different solutions to the same problem (in the system in general, but let alone in the same page)

2022-10-22 10:12 UTC, Aviv-Galmidi commented
The Create / Edit / Delete are not at all what we've discussed
We need to create a modal (popup) similar to the current Reblaze solution, and show/hide it using v-show or v-if
Please look at the current system's modal AddModal.html and if there is anything unclear let's discuss

2022-10-23 07:53 UTC, ux-AylonS commented on src/doc-editors/WebProxyEditor.vue
> +          // this is a mockup data. need to take out as soon as we get certificate to work
I tried to create a certificate but it failed.
I think there is no more use for canonical-name

2022-10-24 19:35 UTC, Aviv-Galmidi requested changes

2022-10-24 19:35 UTC, Aviv-Galmidi commented on src/doc-editors/ConfigTemplatesEditor.vue
> +    sslConfSpecific: {
As we've discussed, `sslConfSpecific` and `confSpecific` should be in the following format
`{"value": (stringValueOfTheseInputs)}`
for example if the input has `test123` in it then the `sslConfSpecific` will be `{"value": "test123"}`

2022-10-24 19:35 UTC, Aviv-Galmidi commented on src/doc-editors/ServerGroupsEditor.vue
> +                <div class="field">
This field should be hidden from the UI until implemented as well

2022-10-25 07:49 UTC, Aviv-Galmidi requested changes

2022-10-25 07:49 UTC, Aviv-Galmidi commented on src/doc-editors/ConfigTemplatesEditor.vue
> +                              v-model="selectedConfigTemplate.conf_specific.value">
This will create issues if `selectedConfigTemplate.conf_specific` doesn't exist, we should add normalization on doc load to make sure we won't get `value of undefined` error

This is an example of a normalization we do in Content Filter Profiles Editor
https://github.com/reblaze/ui/blob/main/src/doc-editors/ContentFilterProfilesEditor.vue#L929
https://github.com/reblaze/ui/blob/main/src/doc-editors/ContentFilterProfilesEditor.vue#L835

We can do something very similar here, but instead of setting the value to an array we'll set it to an object

2022-10-25 07:49 UTC, Aviv-Galmidi commented on src/doc-editors/ConfigTemplatesEditor.vue
> +                              v-model="selectedConfigTemplate.ssl_conf_specific.value">
same as above

2022-10-25 10:27 UTC, Aviv-Galmidi approved these changes

2022-10-25 11:50 UTC, Aviv-Galmidi approved these changes

2022-10-25 12:09 UTC, merged