changes to cloud functions
reblaze/ui pull request #88
Opened 2022-10-19 10:46 UTC by ux-AylonS

Signed-off-by: AylonS <aylons@reblaze.com>

2022-10-19 10:58 UTC, Aviv-Galmidi requested changes

2022-10-19 10:58 UTC, Aviv-Galmidi commented on src/assets/DatasetsUtils.ts
> +  'request1': 'Request Post',
just `Request`

2022-10-19 10:58 UTC, Aviv-Galmidi commented on src/assets/DatasetsUtils.ts
> +  'response0': 'Response Pre',
just `Response`

2022-10-19 10:58 UTC, Aviv-Galmidi commented on src/assets/RequestsUtils.ts
> +const dataLayerAPIVersion = 'v3'
Check with @Freakachoo if this was changed in the API to v3 and if it needs to be changed

2022-10-20 02:53 UTC, ux-AylonS commented on src/assets/DatasetsUtils.ts
> +  'request1': 'Request Post',
not implemented in the backend yet

2022-10-20 02:57 UTC, ux-AylonS commented on src/assets/RequestsUtils.ts
> +const dataLayerAPIVersion = 'v3'
@Freakachoo do we need to change the dataLayer version from v1.0 to v3 ???

2022-10-20 06:53 UTC, Aviv-Galmidi approved these changes

2022-10-20 10:04 UTC, ux-AylonS commented on src/assets/RequestsUtils.ts
> +const dataLayerAPIVersion = 'v3'
confirmed v1.0 for now

2022-10-20 10:05 UTC, merged