Dynamic changes
reblaze/ui pull request #99
Opened 2022-10-23 03:13 UTC by ux-AylonS

2022-10-23 07:51 UTC, Aviv-Galmidi requested changes

2022-10-23 07:51 UTC, Aviv-Galmidi commented on src/router/index.ts
> +              {
We're missing the second child for the config

2022-10-23 07:51 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +            </button>
Changed from `main` branch:

```suggestion
        <div class="field is-grouped is-pulled-right">
          <p class="control">
            <button class="button is-small download-doc-button"
                    :class="{'is-loading':isDownloadLoading}"
                    @click="downloadDoc()"
                    title="Download document"
                    data-qa="download-document">
              <span class="icon is-small">
                <i class="fas fa-download"></i>
              </span>
              <span>
                Download
              </span>
            </button>
```

2022-10-23 07:51 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +        // const completeDoc = {this.dynamicRulesData + this.globalFiltersData}
Let's remove this comment

2022-10-23 07:51 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +      // const config = {headers: {'x-fields': 'id, tags, action'}} returns all fields
I think it was commented out by mistake, we can use it in the /globalfilters/ request

2022-10-23 07:51 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +    async switchBranch() {
Method can be removed

2022-10-23 07:51 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +    await this.branchesStore.list
```suggestion
    this.setLoadingDocStatus(true)
    await this.branchesStore.list
    this.setLoadingDocStatus(false)
```

2022-10-23 07:51 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +    await this.loadDynamicRulesData()
This will be called from the watch on `selectedBranch`

2022-10-23 07:51 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +          this.dynamicRulesDataAndGlobalFilters.push(joinedObject)
This type seems confusing as the data is not really on the same object in the reality (Backend, APIs, etc.)

Why not use `dispalyFunction` like I suggested 

> the list columns will get the data by searching the Global Filters for the id with matching id to the row item

So `Tags` column would look something like
```
    {
      title: 'Tags',
      displayFunction: (item: DynamicRule) => {
        const matchingGlobalFilter = this.globalFiltersData.find((globalFilter: GlobalFilter) => {
         return globalFilter.id === `dr_${item.id}`
        }
        return matchingGlobalFilter.tags?.join('\n')
      },
      isSortable: false,
      isSearchable: true,
      classes: 'width-100px white-space-pre ellipsis',
    },
```
Note: I wrote this code in the GitHub comment section, so make sure it's actually okay in the system

2022-10-23 08:01 UTC, ux-AylonS commented on src/router/index.ts
> +              {
I use DocumentEditor to serve the DynamicRulesEditor,
and it is working well.

2022-10-23 12:20 UTC, ux-AylonS commented on src/views/DynamicRulesList.vue
> +      // const config = {headers: {'x-fields': 'id, tags, action'}} returns all fields
I tried to use it but I still got back the full object and not only the listed columns

2022-10-23 14:01 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
>            this.globalFiltersData.push({id: responseGlobal.data.id, tags: responseGlobal.data.tags,
We can se this.globalFiltersData as responseGlobal.data

2022-10-23 19:22 UTC, ux-AylonS commented on src/views/DynamicRulesList.vue
> +          this.dynamicRulesDataAndGlobalFilters.push(joinedObject)
DONE

2022-10-24 06:53 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
> +              return matchingGlobalFilter ? matchingGlobalFilter.tags?.join('\n') : null
displayFunction should return a string, let's return an empty string if the tags don't exist or there is no global filters data

2022-10-24 12:32 UTC, Aviv-Galmidi requested changes

2022-10-24 12:32 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
>                return []
This should also return an empty string

2022-10-24 19:28 UTC, Aviv-Galmidi commented on src/views/DynamicRulesList.vue
>                return []
Still not fixed

2022-10-24 19:28 UTC, Aviv-Galmidi commented on src/views/documentListConst.ts
> +  'dynamic-rules': [
Did you re-add this by mistake

2022-10-25 06:27 UTC, ux-AylonS commented on src/views/documentListConst.ts
> +  'dynamic-rules': [
yes, deleted

2022-10-25 07:05 UTC, Aviv-Galmidi approved these changes

2022-10-25 07:43 UTC, Aviv-Galmidi approved these changes

2022-10-25 07:47 UTC, merged